import React, { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Crown, RefreshCw, Search, ShieldCheck, Users } from "lucide-react";
import { supabase } from "./supabaseClient.js";

const CSS = `
.bo,.bo *{box-sizing:border-box}.bo{min-height:100vh;background:#f4efe0;color:#14160f;font-family:'Space Grotesk',system-ui,sans-serif}.bo-wrap{width:min(1180px,calc(100% - 32px));margin:auto;padding:42px 0 80px}.bo-head{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;flex-wrap:wrap;margin-bottom:28px}.bo-back{display:inline-flex;align-items:center;gap:6px;color:#14160f;font-weight:700;font-size:13px;margin-bottom:18px}.bo h1{font-family:'Archivo Black',sans-serif;font-size:clamp(30px,5vw,48px);margin:0;text-shadow:3px 3px 0 #cdf564,5px 5px 0 #ff6f59}.bo-sub{color:#626458;margin-top:10px}.bo-actions{display:flex;gap:8px}.bo-btn{display:inline-flex;align-items:center;gap:7px;border:2px solid #14160f;border-radius:999px;background:#cdf564;color:#14160f;text-decoration:none;padding:10px 15px;font-weight:800;cursor:pointer}.bo-btn:disabled{opacity:.55}.bo-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px}.bo-metric,.bo-panel{background:#fff;border:2px solid #14160f;border-radius:18px}.bo-metric{padding:20px}.bo-metric span{display:block;color:#6d7064;font-size:12px;margin-bottom:8px}.bo-metric b{font-family:'Archivo Black',sans-serif;font-size:28px}.bo-panel{overflow:hidden}.bo-toolbar{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:16px;border-bottom:2px solid #14160f}.bo-search{position:relative;flex:1;max-width:420px}.bo-search svg{position:absolute;left:12px;top:12px}.bo-search input{width:100%;height:40px;border:2px solid #14160f;border-radius:999px;padding:0 14px 0 38px;font:inherit;background:#f4efe0}.bo-count{font-size:12px;color:#6d7064}.bo-table-wrap{overflow:auto}.bo-table{width:100%;border-collapse:collapse;min-width:820px}.bo-table th,.bo-table td{text-align:left;padding:14px 16px;border-bottom:1px solid #dedbcf;font-size:13px}.bo-table th{font-size:11px;text-transform:uppercase;letter-spacing:.06em;background:#f7f4ea}.bo-status{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800;background:#eceee7}.bo-status.active{background:#cdf564}.bo-dot{width:7px;height:7px;border-radius:50%;background:#888}.bo-status.active .bo-dot{background:#315c43}.bo-empty,.bo-error{padding:42px;text-align:center;color:#6d7064}.bo-error{color:#a53a2a}.bo-secure{display:flex;align-items:center;gap:6px;margin-top:18px;color:#6d7064;font-size:11px}
.bo-finance{background:#fff;border:2px solid #14160f;border-radius:18px;padding:20px;margin-bottom:24px}.bo-finance-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:16px}.bo-finance h2{font-size:17px;margin:0}.bo-finance small{color:#6d7064}.bo-finance-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.bo-finance-item{padding:15px;border-radius:12px;background:#f4efe0}.bo-finance-item span{display:block;color:#6d7064;font-size:11px;margin-bottom:6px}.bo-finance-item b{font-size:19px}.bo-breakdown{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.bo-breakdown span{padding:7px 10px;border-radius:999px;background:#edf5e7;font-size:11px;font-weight:700}.bo-private{padding:22px;text-align:center;background:#f4efe0;border-radius:12px;color:#626458;font-size:13px}.bo-pro{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:999px;background:#eceee7;font-size:10px;font-weight:900;white-space:nowrap}.bo-pro.active{background:#cdf564}.bo-member-actions{display:flex;gap:6px;min-width:245px}.bo-member-btn{border:1.5px solid #14160f;border-radius:999px;background:#fff;padding:7px 9px;font:inherit;font-size:9px;font-weight:900;cursor:pointer;white-space:nowrap}.bo-member-btn.manage{background:#eaf5ff}.bo-member-btn.danger{background:#ffe2dc;color:#9d2f20}.bo-member-btn:disabled{opacity:.5;cursor:wait}.bo-admin-message{margin:0 0 12px;padding:10px 12px;border:1px solid #bddf77;border-radius:11px;background:#edf8d5;font-size:11px;font-weight:700}.bo-admin-message.error{border-color:#f0a396;background:#ffe2dc;color:#9d2f20}
@media(max-width:800px){.bo-metrics,.bo-finance-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.bo-metrics,.bo-finance-grid{grid-template-columns:1fr}.bo-wrap{width:min(100% - 20px,1180px)}}`;
const tarih = (v) => v ? new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(v)) : "—";
const para = (v) => new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY", maximumFractionDigits: 0 }).format(v || 0);

export default function Backoffice() {
  const [veri, setVeri] = useState(null); const [hata, setHata] = useState(""); const [yukleniyor, setYukleniyor] = useState(true); const [ara, setAra] = useState("");
  const [islemde,setIslemde]=useState(""),[onayId,setOnayId]=useState(""),[yonetimMesaji,setYonetimMesaji]=useState(null),[yonetimUrl,setYonetimUrl]=useState("");
  async function yukle() {
    setYukleniyor(true); setHata("");
    const { data: sessionData } = await supabase.auth.getSession();
    const token = sessionData.session?.access_token;
    try {
      const cevap = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/backoffice`, { headers: { Authorization: `Bearer ${token}` } });
      const json = await cevap.json(); if (!cevap.ok) throw new Error(json.error); setVeri(json);
    } catch (e) { setHata(e.message === "FORBIDDEN" ? "Bu hesabın backoffice yetkisi yok." : "Backoffice verileri alınamadı."); }
    finally { setYukleniyor(false); }
  }
  useEffect(() => { yukle(); }, []);
  const kullanicilar = useMemo(() => (veri?.users || []).filter((x) => x.email.toLocaleLowerCase("tr-TR").includes(ara.toLocaleLowerCase("tr-TR"))), [veri, ara]);
  async function proIslemi(userId,action){
    if(action==="revoke_pro"&&onayId!==userId){setOnayId(userId);setYonetimMesaji(null);return}
    setIslemde(`${userId}:${action}`);setYonetimMesaji(null);setYonetimUrl("");
    try{const{data}=await supabase.auth.getSession();const cevap=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/backoffice`,{method:"POST",headers:{Authorization:`Bearer ${data.session?.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({userId,action})});const json=await cevap.json();if(!cevap.ok)throw new Error(json.error);if(action==="manage_pro"){setYonetimUrl(json.managementURL);setYonetimMesaji({tur:"ok",metin:"Güvenli abonelik yönetim bağlantısı hazır."});return}setVeri(eski=>({...eski,users:(eski?.users||[]).map(u=>u.id===userId?{...u,pro_active:action==="grant_pro",pro_expires_at:json.proExpiresAt||null,pro_source:action==="grant_pro"?"admin_manual":"admin_revoked"}:u)}));setYonetimMesaji({tur:"ok",metin:action==="grant_pro"?"Kullanıcıya 30 gün Pro tanımlandı.":"Kullanıcı Ücretsiz pakete geçirildi; finansal verileri korunuyor."});setOnayId("")}catch(e){const kod=e?.message;setYonetimMesaji({tur:"error",metin:kod==="PAID_SUBSCRIPTION_NOT_FOUND"?"Bu kullanıcı için yönetilecek ücretli abonelik bulunamadı.":kod==="REVENUECAT_SECRET_NOT_CONFIGURED"?"Abonelik yönetimi sunucu tarafında henüz bağlanmamış.":"Paket işlemi tamamlanamadı."})}finally{setIslemde("")}
  }
  return <div className="bo"><style>{CSS}</style><div className="bo-wrap"><a className="bo-back" href="/summary"><ArrowLeft size={15}/> Uygulamaya dön</a><div className="bo-head"><div><h1>Borcama Backoffice</h1><div className="bo-sub">Kullanıcı girişleri ve hesap durumları</div></div><div className="bo-actions"><a className="bo-btn" href="/ceo">CEO ekranı</a><button className="bo-btn" onClick={yukle} disabled={yukleniyor}><RefreshCw size={15}/> Yenile</button></div></div>
  <div className="bo-metrics"><Metric ad="Toplam kullanıcı" deger={veri?.summary.total}/><Metric ad="Son 30 gün aktif" deger={veri?.summary.active_30d}/><Metric ad="Son 7 gün giriş" deger={veri?.summary.signed_in_7d}/><Metric ad="Son 7 gün yeni" deger={veri?.summary.new_7d}/></div>
  <Finansal veri={veri?.financial}/>
  <div className="bo-panel"><div className="bo-toolbar"><div className="bo-search"><Search size={16}/><input value={ara} onChange={(e)=>setAra(e.target.value)} placeholder="E-posta ara"/></div><div className="bo-count"><Users size={13}/> {kullanicilar.length} kullanıcı</div></div>
  {yonetimMesaji&&<div className={`bo-admin-message ${yonetimMesaji.tur}`}>{yonetimMesaji.metin}{yonetimUrl&&<> <a href={yonetimUrl} target="_blank" rel="noreferrer">Paddle yönetimini aç</a></>}</div>}
  {yukleniyor?<div className="bo-empty">Yükleniyor…</div>:hata?<div className="bo-error">{hata}</div>:<div className="bo-table-wrap"><table className="bo-table"><thead><tr><th>Kullanıcı</th><th>Durum</th><th>Paket</th><th>Kayıt tarihi</th><th>Son giriş</th><th>Veri</th><th>Paket işlemleri</th></tr></thead><tbody>{kullanicilar.map((u)=><tr key={u.id}><td>{u.email}</td><td><span className={`bo-status ${u.status}`}><i className="bo-dot"/>{u.status==="active"?"Aktif":"Pasif"}</span></td><td><span className={`bo-pro ${u.pro_active?"active":""}`}><Crown size={11}/>{u.pro_active?"Pro":"Ücretsiz"}</span></td><td>{tarih(u.created_at)}</td><td>{tarih(u.last_sign_in_at)}</td><td>{u.has_data?"Var":"Yok"}</td><td><div className="bo-member-actions">{u.pro_active?<><button className="bo-member-btn manage" disabled={!!islemde} onClick={()=>proIslemi(u.id,"manage_pro")}>Yenilemeyi yönet</button><button className="bo-member-btn danger" disabled={!!islemde} onClick={()=>proIslemi(u.id,"revoke_pro")}>{onayId===u.id?"Geçişi onayla":"Ücretsiz pakete geçir"}</button></>:<button className="bo-member-btn" disabled={!!islemde} onClick={()=>proIslemi(u.id,"grant_pro")}>30 gün Pro tanımla</button>}</div></td></tr>)}</tbody></table></div>}</div><div className="bo-secure"><ShieldCheck size={13}/> Paket değişiklikleri finansal kayıtları silmez. Ücretli aboneliğin yenilenmesi Paddle yönetiminden ayrıca durdurulur.</div></div></div>;
}
function Metric({ad,deger}){return <div className="bo-metric"><span>{ad}</span><b>{deger ?? "—"}</b></div>}
function Finansal({veri}){if(!veri)return null;return <section className="bo-finance"><div className="bo-finance-head"><h2>Anonim finansal görünüm</h2><small>{veri.participant_count} hesap dahil</small></div>{!veri.available?<div className="bo-private">Gizliliği korumak için toplu istatistikler en az {veri.minimum_required} finansal veri sahibi kullanıcı olduğunda gösterilir.</div>:<><div className="bo-finance-grid"><FinansKalem ad="Toplam borç" deger={para(veri.total_debt)}/><FinansKalem ad="Bu ay gelir" deger={para(veri.monthly_income)}/><FinansKalem ad="Bu ay harcama" deger={para(veri.monthly_expense)}/><FinansKalem ad="Borç / aylık gelir" deger={veri.debt_to_monthly_income==null?"—":veri.debt_to_monthly_income.toLocaleString("tr-TR",{maximumFractionDigits:1})+" kat"}/></div><div className="bo-breakdown"><span>Kartlar: {para(veri.breakdown.cards)}</span><span>Krediler: {para(veri.breakdown.loans)}</span><span>KMH: {para(veri.breakdown.overdrafts)}</span><span>Diğer: {para(veri.breakdown.others)}</span></div></>}</section>}
function FinansKalem({ad,deger}){return <div className="bo-finance-item"><span>{ad}</span><b>{deger}</b></div>}
