export const FINANSAL_SOZLUK_GUNCELLEME_TARIHI = "2026-09-23";

export const FINANSAL_SOZLUK = [
  {
    slug: "faiz",
    title: "Faiz",
    category: "Faiz ve maliyet",
    definition: "Paranın belirli bir süre kullanılmasının karşılığında ödenen veya kazanılan tutar ya da orandır.",
    detail: "Faiz tek bir kavram gibi görünse de borçta ve birikimde farklı sonuç üretir. Kredide maliyet, mevduatta getiri olabilir; nominal oran, efektif oran, akdi faiz ve gecikme faizi birbirinin yerine kullanılmamalıdır.",
    example: "100.000 TL borca aylık yüzde 3 oran uygulanması, vergi ve diğer maliyetler hariç ilk ay için yaklaşık 3.000 TL faiz anlamına gelebilir; kesin hesap ürün koşullarına bağlıdır.",
    borcama: "Borcama, kullanıcı oran girdiyse bu oranı; oran yoksa uygun ürün için güncel resmî referansı tahmin olarak kullanır ve faiz ile anaparayı ayrı gösterir.",
    related: ["akdi-faiz", "gecikme-faizi", "efektif-faiz-orani"],
    tool: "borc-kapatma-hesaplayici",
  },
  {
    slug: "temerrut",
    title: "Temerrüt",
    category: "Borç yönetimi",
    definition: "Bir borçlunun vadesi gelmiş yükümlülüğünü gereken zamanda ve koşullarda yerine getirmemesi durumudur.",
    detail: "Temerrüt yalnızca 'borcun bulunması' anlamına gelmez; ödeme yükümlülüğünün muaccel olması ve zamanında yerine getirilmemesiyle ilgilidir. Sonuçları sözleşmeye, borcun türüne ve mevzuata göre değişebileceğinden banka bildirimi veya hukuki belge esas alınmalıdır.",
    example: "Vadesi 15 Eylül olan bir taksit sözleşmede belirtilen süre ve koşullarda ödenmezse gecikme ve temerrüt hükümleri gündeme gelebilir.",
    borcama: "Yaklaşan ödeme günlerini aynı takvimde görmek, ödeme vadesi geçmeden eksik bütçeyi fark etmene yardımcı olur; Borcama hukuki durum tespiti yapmaz.",
    related: ["temerrut-faizi", "son-odeme-tarihi", "gecikme-faizi"],
    tool: "aylik-odeme-takvimi",
  },
  {
    slug: "temerrut-faizi",
    title: "Temerrüt faizi",
    category: "Faiz ve maliyet",
    definition: "Vadesinde yerine getirilmeyen para borcu için temerrüt döneminde uygulanabilen faizdir.",
    detail: "Temerrüt faizi ile normal sözleşme faizi aynı kavram değildir. Oranın kaynağı, hangi tutara uygulanacağı ve başlangıç tarihi borcun türüne, sözleşmeye ve güncel mevzuata göre değişebilir; banka veya alacaklı tarafından bildirilen hesap kontrol edilmelidir.",
    example: "Bir taksidin vadesi geçtiğinde hesaplanan ek maliyet, normal dönem faizinden farklı bir temerrüt kuralına dayanabilir.",
    borcama: "Borcama geciken tutarı ve ödeme tarihini görünür kılar; kesin temerrüt maliyetini banka belgesi olmadan kesinmiş gibi sunmaz.",
    related: ["temerrut", "gecikme-faizi", "akdi-faiz"],
  },
  {
    slug: "tasfiye",
    title: "Tasfiye",
    category: "Borç yönetimi",
    definition: "Bir hesap, borç, varlık veya kurumla ilgili mali ilişkilerin sonuçlandırılıp kapatılması sürecidir.",
    detail: "Finansal bağlama göre tasfiye; borcun kapatılması, bir varlığın nakde çevrilmesi veya bir kurumun alacak ve yükümlülüklerinin sonuçlandırılması anlamına gelebilir. Günlük aramalarda 'tasviye' diye de yazılsa da doğru yazım 'tasfiye'dir; işlemin hukuki sonucu ilgili belgeye göre değerlendirilir.",
    example: "Bir borcun tasfiye edilmesi, ödeme veya mutabakat sonunda borç ilişkisinin kapatılması anlamına gelebilir; yalnızca taksit sayısının bitmesi her durumda aynı hukuki sonucu göstermeyebilir.",
    borcama: "Borcama'da bir borcun kalan tutarı sıfırlandığında finansal takip tamamlanır; resmî kapanış ve ibra için banka ya da alacaklı belgesi esas alınır.",
    related: ["borc-yapilandirma", "kalan-anapara", "toplam-geri-odeme"],
  },
  {
    slug: "asgari-odeme",
    title: "Asgari ödeme",
    category: "Kredi kartı",
    definition: "Kredi kartı ekstresinde, son ödeme tarihine kadar ödenmesi gereken en düşük tutardır.",
    detail: "Asgari ödeme, kartın dönem borcunun tamamını kapatmaz. Yalnızca bankanın o ekstre için bildirdiği alt ödeme eşiğini gösterir; ödenmeyen bölüm sonraki döneme taşınır ve sözleşme ile güncel mevzuata göre maliyet doğurabilir.",
    example: "Dönem borcun 20.000 TL ve ekstredeki asgari ödeme 8.000 TL ise 8.000 TL ödemek kartı tamamen kapatmaz. Kalan 12.000 TL devreden bakiye olur.",
    borcama: "Borcama'da dönem borcu, asgari ödeme ve yaptığın ödeme ayrı tutulur; böylece yalnızca asgariyi ödediğinde geriye ne kaldığını görebilirsin.",
    related: ["donem-borcu", "devreden-bakiye", "akdi-faiz"],
    tool: "kredi-karti-asgari-odeme-hesaplayici",
  },
  {
    slug: "donem-borcu",
    title: "Dönem borcu",
    category: "Kredi kartı",
    definition: "Bir kredi kartı hesap kesim döneminde ekstreye yansıyan toplam borçtur.",
    detail: "Dönem borcu; o dönemde ekstreye giren alışveriş, taksit, nakit çekim, ücret, önceki dönemden taşınan tutar ve varsa maliyetlerden oluşabilir. Güncel borçla aynı şey değildir; hesap kesiminden sonra yaptığın yeni işlemler güncel borca eklenir ama ilgili ekstreye girmez.",
    example: "Ekstren 5 Eylül'de kesildiyse o tarihe kadar ekstreleşen 18.500 TL dönem borcudur. 6 Eylül'deki yeni harcama bir sonraki döneme kalabilir.",
    borcama: "Kart eklerken dönem borcunu ekstrendeki değerle kaydetmek, asgari ödeme ve kalan borç hesabının doğru başlamasını sağlar.",
    related: ["kredi-karti-ekstresi", "asgari-odeme", "son-odeme-tarihi"],
  },
  {
    slug: "devreden-bakiye",
    title: "Devreden bakiye",
    category: "Kredi kartı",
    definition: "Kredi kartı dönem borcundan yapılan ödemeler çıktıktan sonra sonraki döneme taşınan tutardır.",
    detail: "Dönem borcunun tamamı son ödeme tarihine kadar kapatılmadığında kalan bölüm devreden bakiye haline gelir. Yeni harcamalar, maliyetler ve sonraki ödemeler bu bakiyeyi değiştirebilir; bu yüzden yalnızca kart limitine bakmak gerçek borç durumunu göstermez.",
    example: "24.000 TL dönem borcuna 10.000 TL ödeme yaptıysan, başka düzeltme yoksa 14.000 TL sonraki döneme devreder.",
    borcama: "Ödeme girdikçe kalan kart borcu güncellenir; devreden tutarı diğer kart ve kredilerinden ayrı görebilirsin.",
    related: ["donem-borcu", "akdi-faiz", "gecikme-faizi"],
  },
  {
    slug: "kredi-karti-ekstresi",
    title: "Kredi kartı ekstresi",
    category: "Kredi kartı",
    definition: "Kartın belirli hesap dönemindeki işlemlerini, borcunu ve ödeme tarihlerini gösteren banka belgesidir.",
    detail: "Ekstrede dönem borcu, asgari ödeme, hesap kesim tarihi, son ödeme tarihi, taksitler, ücretler ve dönem içi işlemler yer alabilir. Güncel kart bakiyesiyle karıştırılmamalıdır; ekstre kesildikten sonraki işlemler henüz bu belgede bulunmaz.",
    example: "Eylül ekstresi 6 Ağustos–5 Eylül arasındaki işlemleri gösterebilir. 6 Eylül'de yapılan alışveriş çoğunlukla bir sonraki ekstreye yansır.",
    borcama: "Ekstre dosyası cihazında okunur; kaydetmeden önce dönem borcunu ve işlem kategorilerini sen kontrol edersin.",
    related: ["donem-borcu", "hesap-kesim-tarihi", "son-odeme-tarihi"],
  },
  {
    slug: "hesap-kesim-tarihi",
    title: "Hesap kesim tarihi",
    category: "Kredi kartı",
    definition: "Kredi kartının o ayki ekstresine girecek işlemlerin hesaplandığı tarihtir.",
    detail: "Hesap kesim tarihi geldiğinde banka ilgili dönemin ekstresini oluşturur. Bu tarihten sonra yapılan işlemler genellikle sonraki ekstre dönemine kalır; ancak kesin yansıma zamanı işlemin bankada muhasebeleşmesine göre değişebilir.",
    example: "Hesap kesim tarihin ayın 10'uysa, 11'inde muhasebeleşen bir harcama çoğunlukla sonraki ayın ekstresinde görünür.",
    borcama: "Kart kaydındaki hesap kesim tarihi, hangi borcun hangi ayın planına ait olduğunu ayırmana yardımcı olur.",
    related: ["kredi-karti-ekstresi", "son-odeme-tarihi", "donem-borcu"],
  },
  {
    slug: "son-odeme-tarihi",
    title: "Son ödeme tarihi",
    category: "Kredi kartı",
    definition: "Ekstrede belirtilen ödemenin gecikmeye düşmeden yapılması gereken son gündür.",
    detail: "Son ödeme tarihi hesap kesim tarihinden farklıdır. Banka bu tarihe kadar en az ekstredeki asgari tutarın ödenmesini bekler; tatil günü ve işlem saati gibi ayrıntılar için bankanın bildirimini esas almak gerekir.",
    example: "Ekstre 8 Eylül'de kesilip son ödeme tarihi 18 Eylül olarak belirlenmişse, planında ödeme gününü 18 Eylül'den önceye koyabilirsin.",
    borcama: "Ödeme günlerini aylık takvimde sıralayarak yaklaşan kart ve kredi ödemelerini birlikte görebilirsin.",
    related: ["hesap-kesim-tarihi", "asgari-odeme", "gecikme-faizi"],
    tool: "aylik-odeme-takvimi",
  },
  {
    slug: "akdi-faiz",
    title: "Akdi faiz",
    category: "Faiz ve maliyet",
    definition: "Kredi veya kart sözleşmesinde belirlenen, borcun normal kullanım koşullarındaki faiz oranıdır.",
    detail: "Akdi faiz ile gecikme faizi aynı değildir. Hangi bakiyeye, hangi tarihler arasında ve hangi vergilerle uygulanacağı ürün sözleşmesine bağlıdır; kredi kartlarında güncel azami oranlar TCMB tarafından yayımlanır.",
    example: "Kart borcunun tamamını kapatmadığında devreden tutara uygulanacak normal dönem maliyetinin temel bileşenlerinden biri akdi faizdir.",
    borcama: "Kendi oranını girdiysen hesaplarda o kullanılır; oran yoksa uygun ürün için güncel resmî referans ayrı bir tahmin olarak değerlendirilir.",
    related: ["gecikme-faizi", "efektif-faiz-orani", "bsmv"],
    tool: "borc-kapatma-hesaplayici",
  },
  {
    slug: "gecikme-faizi",
    title: "Gecikme faizi",
    category: "Faiz ve maliyet",
    definition: "Ödenmesi gereken tutar vadesinde ödenmediğinde geciken bölüm için uygulanabilen faizdir.",
    detail: "Gecikme faizinin matrahı ve başlangıç tarihi ürünün türüne ve sözleşmesine göre değişir. Kredi kartı, kredi taksiti ve ek hesap aynı kuralla hesaplanmayabilir; kesin tutar için banka ekstresi ve ödeme planı esas alınmalıdır.",
    example: "Son ödeme tarihinde gereken tutarın bir kısmı eksik kalırsa banka, geciken bölüm için sözleşmedeki kurala göre maliyet hesaplayabilir.",
    borcama: "Ödeme tarihlerini tek takvimde tutmak, gecikme riskini ödeme gerçekleşmeden görmene yardımcı olur.",
    related: ["akdi-faiz", "son-odeme-tarihi", "devreden-bakiye"],
  },
  {
    slug: "efektif-faiz-orani",
    title: "Efektif faiz oranı",
    category: "Faiz ve maliyet",
    definition: "Bir finansman ürününün faiz dışındaki zorunlu maliyetlerini ve zaman etkisini de hesaba katan karşılaştırma oranıdır.",
    detail: "İlan edilen nominal oran tek başına kredinin toplam maliyetini göstermeyebilir. Efektif oran, ödeme sıklığı ve zorunlu maliyetleri ortak bir ölçüye çevirmeyi amaçlar; farklı ürünleri aynı vade ve tutarda karşılaştırırken daha açıklayıcıdır.",
    example: "Aynı aylık faiz oranını sunan iki krediden biri ek zorunlu maliyet içeriyorsa efektif maliyeti daha yüksek olabilir.",
    borcama: "Kredi kaydında yalnızca taksite değil, toplam geri ödemeye ve kalan maliyete birlikte bakmak karşılaştırmayı kolaylaştırır.",
    related: ["akdi-faiz", "toplam-geri-odeme", "aylik-taksit"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "bsmv",
    title: "BSMV",
    category: "Faiz ve maliyet",
    definition: "Banka ve Sigorta Muameleleri Vergisi'nin kısaltmasıdır; bazı bankacılık işlemlerinde verginin bir parçası olarak tahsil edilir.",
    detail: "BSMV'nin uygulanıp uygulanmadığı ve matrahı işlem türüne göre değişebilir. Faiz oranıyla aynı şey değildir; kredi, kart veya ek hesap maliyetini hesaplarken sözleşmede gösterilen vergi kalemleri ayrıca kontrol edilmelidir.",
    example: "Bir finansman maliyeti faiz ve BSMV kalemlerini ayrı gösteriyorsa toplam aylık yük bu kalemlerin birlikte değerlendirilmesiyle bulunur.",
    borcama: "Borç planında banka oranı ve ilgili vergi bileşenleri ayrı tutulabildiği için tahminin dayanağını görebilirsin.",
    related: ["kkdf", "akdi-faiz", "efektif-faiz-orani"],
  },
  {
    slug: "kkdf",
    title: "KKDF",
    category: "Faiz ve maliyet",
    definition: "Kaynak Kullanımını Destekleme Fonu kesintisinin kısaltmasıdır ve bazı kredi işlemlerinde maliyete eklenebilir.",
    detail: "KKDF her finansman ürününde aynı biçimde uygulanmaz. Ürün türü, kullanım amacı ve güncel mevzuat sonucu etkileyebileceğinden kesin oranı kredi sözleşmesi ve banka ödeme planından kontrol etmek gerekir.",
    example: "Kredi ödeme planında faiz, BSMV ve KKDF ayrı satırlarda gösteriliyorsa taksit maliyeti bu bileşenlerin toplamını içerir.",
    borcama: "Ödeme planını aktarırken kalan anapara ile kalan faiz ve masrafı ayırmak, toplam yükü daha doğru okumana yardım eder.",
    related: ["bsmv", "toplam-geri-odeme", "kalan-anapara"],
  },
  {
    slug: "kalan-anapara",
    title: "Kalan anapara",
    category: "Kredi",
    definition: "Bir kredide, yapılan anapara ödemeleri düşüldükten sonra henüz geri ödenmemiş asıl borç tutarıdır.",
    detail: "Kalan anapara, kalan taksitlerin toplamı değildir. Gelecek taksitler çoğunlukla anapara ile birlikte faiz, vergi ve diğer sözleşmesel maliyetleri de içerir; bu nedenle toplam ödeme kalan anaparadan yüksek olabilir.",
    example: "Kalan anapara 100.000 TL iken gelecekteki taksitlerin toplamı 118.000 TL olabilir. Aradaki fark planlanan faiz ve diğer maliyetlerden oluşur.",
    borcama: "Kredi kartında kalan anapara, kalan toplam ödeme ve kalan faiz/masraf ayrı alanlarda gösterilir.",
    related: ["toplam-geri-odeme", "aylik-taksit", "borc-yapilandirma"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "toplam-geri-odeme",
    title: "Toplam geri ödeme",
    category: "Kredi",
    definition: "Bir kredi veya yapılandırmada ödeme planı boyunca ödenecek taksitlerin toplamıdır.",
    detail: "Toplam geri ödeme; anapara, faiz ve sözleşmeye göre taksitlere yansıyan diğer maliyetleri içerir. Erken ödeme, gecikme veya oran değişikliği gibi durumlarda gerçek toplam ödeme ilk plandan farklılaşabilir.",
    example: "36 ay boyunca 5.000 TL taksit ödenecekse planlanan toplam geri ödeme 180.000 TL'dir; bunun tamamı anapara değildir.",
    borcama: "Kredi satırında kalan taksit sayısı ile aylık taksiti kullanarak kalan toplam ödemeyi, anaparadan ayrı izleyebilirsin.",
    related: ["kalan-anapara", "aylik-taksit", "efektif-faiz-orani"],
  },
  {
    slug: "aylik-taksit",
    title: "Aylık taksit",
    category: "Kredi",
    definition: "Kredi ödeme planında belirli bir ay için ödenmesi planlanan tutardır.",
    detail: "Taksit yalnızca anapara ödemesinden oluşmaz; plana göre faiz ve diğer maliyetler de içerebilir. Eşit taksitli bir kredide tutar sabit görünse de taksit içindeki anapara ve faiz dağılımı zamanla değişebilir.",
    example: "Aylık taksitin 7.500 TL olması, anaparanın her ay tam 7.500 TL azalacağı anlamına gelmez.",
    borcama: "Aylık taksitler ödeme gününe göre takvime gelir; ödediğinde ilgili ayın kaydı ve kalan taksit bilgisi güncellenir.",
    related: ["kalan-anapara", "toplam-geri-odeme", "son-odeme-tarihi"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "ek-hesap-kmh",
    title: "Ek hesap (KMH)",
    category: "Borç yönetimi",
    definition: "Vadesiz hesaba tanımlanan ve bakiye yetersizken kullanılabilen kredili mevduat hesabıdır.",
    detail: "KMH kullanıldığında hesap eksi bakiyeye geçer ve kullanılan tutar için ürün koşullarına göre maliyet oluşabilir. Limit, kullanılabilir tutarı; açık bakiye ise gerçekten kullanılan borcu gösterir. Bu iki rakam aynı değildir.",
    example: "50.000 TL limitli ek hesabın 12.000 TL eksi bakiyedeyse açık borcun 12.000 TL, kalan kullanılabilir limitin kabaca 38.000 TL'dir.",
    borcama: "Ek hesap borcunu sıfırladıktan sonra yeniden kullandığında aynı hesaba yeni borç ekleyebilir ve eski ödemeleri koruyabilirsin.",
    related: ["nakit-akisi", "akdi-faiz", "borc-yapilandirma"],
  },
  {
    slug: "borc-yapilandirma",
    title: "Borç yapılandırma",
    category: "Borç yönetimi",
    definition: "Mevcut borcun yeni vade, taksit veya maliyet koşullarıyla yeniden ödeme planına bağlanmasıdır.",
    detail: "Yapılandırma aylık ödemeyi düşürebilir ama vade uzadığında toplam geri ödeme artabilir. Karar verirken yalnızca yeni taksite değil, toplam maliyete, erken ödeme koşullarına ve mevcut borcun nasıl kapanacağına birlikte bakılmalıdır.",
    example: "Aylık 15.000 TL ödeme 8.000 TL'ye düşerken vade uzuyorsa kısa vadeli rahatlama karşılığında toplam geri ödeme yükselebilir.",
    borcama: "Yapılandırılmış borcu kart bakiyesinden ayırıp ayrı kredi planı olarak izlemek çifte sayımı önler.",
    related: ["toplam-geri-odeme", "aylik-taksit", "efektif-faiz-orani"],
    tool: "borc-odeme-plani",
  },
  {
    slug: "nakit-akisi",
    title: "Nakit akışı",
    category: "Bütçe",
    definition: "Belirli bir dönemde giren ve çıkan paranın zaman ve tutar olarak hareketidir.",
    detail: "Gelir toplamının gider toplamından yüksek olması tek başına yeterli olmayabilir; ödeme günleri maaştan önce geliyorsa ay içinde geçici açık oluşabilir. Nakit akışı bu nedenle hem tutarı hem de zamanı birlikte ele alır.",
    example: "Ayda 50.000 TL gelir ve 45.000 TL giderin olsa bile 30.000 TL ödeme maaştan önceyse kısa süreli nakit ihtiyacı doğabilir.",
    borcama: "Gelir, sabit gider ve ödeme günlerini aynı ayda görerek hangi tarihte ne kadar alanın kaldığını takip edebilirsin.",
    related: ["butce-acigi", "net-varlik", "son-odeme-tarihi"],
    tool: "aylik-odeme-takvimi",
  },
  {
    slug: "butce-acigi",
    title: "Bütçe açığı",
    category: "Bütçe",
    definition: "Bir dönemde planlanan gider ve ödemelerin kullanılabilir gelirden fazla olmasıdır.",
    detail: "Bütçe açığı her zaman toplam servetin negatif olduğu anlamına gelmez. Aylık gelir-gider dengesi ile net varlık farklı ölçülerdir; düzenli açık sürerse borçlanma veya varlık tüketimi gerektirebilir.",
    example: "Aylık kullanılabilir gelirin 40.000 TL, gider ve zorunlu ödemelerin 47.000 TL ise planlanan açık 7.000 TL'dir.",
    borcama: "Aylık planda gelir, zorunlu ödeme ve yaşam giderlerini bir araya getirerek açığın hangi kalemlerden oluştuğunu görebilirsin.",
    related: ["nakit-akisi", "net-varlik", "borc-kapatma-plani"],
  },
  {
    slug: "net-varlik",
    title: "Net varlık",
    category: "Bütçe",
    definition: "Toplam varlıklardan toplam borçlar çıkarıldığında kalan finansal değerdir.",
    detail: "Net varlık aylık nakit akışından farklıdır. O ay gelir fazlan olabilir ama toplam borçların varlıklarından yüksekse net varlığın negatif kalabilir; düzenli takip yönün iyileşip iyileşmediğini gösterir.",
    example: "300.000 TL varlığın ve 220.000 TL toplam borcun varsa net varlığın 80.000 TL'dir.",
    borcama: "Nakit, mevduat ve diğer varlıkları borçlarınla aynı tabloda izleyerek net durumdaki değişimi görebilirsin.",
    related: ["nakit-akisi", "butce-acigi", "kalan-anapara"],
  },
  {
    slug: "borc-kapatma-plani",
    title: "Borç kapatma planı",
    category: "Borç yönetimi",
    definition: "Borçların hangi sırayla ve hangi aylık bütçeyle azaltılacağını gösteren uygulanabilir ödeme yol haritasıdır.",
    detail: "Sağlıklı plan, bütün borçları ve zorunlu ödemeleri görür; sürdürülebilir aylık bütçeyi kullanır ve kapanan borcun ödemesini sıradaki borca aktarır. En yüksek maliyeti veya en küçük bakiyeyi önceleme gibi farklı yöntemler seçilebilir.",
    example: "Bir kart kapandığında ona ayırdığın 4.000 TL'yi harcamaya döndürmek yerine sıradaki borcun ödemesine eklemek planı hızlandırır.",
    borcama: "Borç Planı kart, kredi ve ek hesaplarını gelir-gider tablonla birlikte değerlendirerek kapanış sırası oluşturur.",
    related: ["borc-yapilandirma", "butce-acigi", "toplam-geri-odeme"],
    tool: "borc-odeme-plani",
  },
  {
    slug: "anapara",
    title: "Anapara",
    category: "Kredi",
    definition: "Borç alınan veya yatırıma başlangıçta konulan, faiz ve diğer maliyetler hariç temel para tutarıdır.",
    detail: "Kredide anapara, bankadan kullanılan asıl tutarı ifade eder. Yapılan her taksidin tamamı anaparayı azaltmaz; taksit içinde faiz, vergi ve ücretler bulunabileceği için kalan anapara ödeme planına göre izlenir.",
    example: "150.000 TL kredi kullandıysan başlangıç anaparan 150.000 TL'dir. Toplam geri ödemen 190.000 TL olsa bile aradaki 40.000 TL anapara değildir.",
    borcama: "Kredi ödeme planı yüklendiğinde anapara, kalan toplam ödeme ve finansman maliyeti ayrı gösterilir; böylece aynı rakamlar birbirine karışmaz.",
    related: ["kalan-anapara", "toplam-geri-odeme", "faiz"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "vade",
    title: "Vade",
    category: "Kredi",
    definition: "Bir borcun ödenmesi veya bir finansal işlemin tamamlanması için belirlenen süre ya da son tarihtir.",
    detail: "Vade bazen tek bir son tarihi, bazen de kredinin toplam ay sayısını anlatır. Vade uzadığında aylık taksit düşebilir; ancak diğer koşullar aynıysa toplam finansman maliyeti artabilir.",
    example: "24 ay vadeli kredi, ödeme planının 24 aylık döneme yayıldığını gösterir. Her taksidin ayrıca kendi ödeme günü bulunur.",
    borcama: "Vade ve ilk taksit tarihi birlikte kaydedilir; böylece kredi doğru ayda başlar ve kalan taksit sayısı ödeme yaptıkça ilerler.",
    related: ["aylik-taksit", "son-odeme-tarihi", "toplam-geri-odeme"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "erken-odeme",
    title: "Erken ödeme",
    category: "Kredi",
    definition: "Bir kredi taksidinin veya borcun sözleşmedeki ödeme tarihinden önce kısmen ya da tamamen ödenmesidir.",
    detail: "Erken ödeme, kalan anapara ve gelecekte işleyecek maliyetleri etkileyebilir. Kısmi ödeme, ara ödeme veya krediyi tamamen kapatma aynı işlem değildir; bankanın yeni ödeme planı ve varsa ücret/indirim hesabı kontrol edilmelidir.",
    example: "Kalan anaparanın 20.000 TL'sini vadesinden önce ödemek, bankanın seçeneğine göre taksit tutarını veya kalan vadeyi değiştirebilir.",
    borcama: "Yaptığın ödemeyi ilgili krediye kaydedebilirsin; bankanın oluşturduğu yeni ödeme planı varsa kalan toplamı güncellemek için planı yeniden aktarmalısın.",
    related: ["ara-odeme", "kalan-anapara", "toplam-geri-odeme"],
  },
  {
    slug: "ara-odeme",
    title: "Ara ödeme",
    category: "Kredi",
    definition: "Kredi devam ederken normal taksitlere ek olarak anaparayı azaltmak amacıyla yapılan toplu ödemedir.",
    detail: "Ara ödeme krediyi tamamen kapatmaz; kalan anaparayı azaltıp yeni bir ödeme planı oluşturabilir. Banka, kalan vadeyi kısaltma veya taksiti düşürme seçenekleri sunabilir ve hesap yöntemi sözleşmeye göre değişebilir.",
    example: "Aylık taksitini ödemeye devam ederken 30.000 TL ek ödeme yaparsan banka kalan anaparaya göre yeni taksit veya vade hesaplayabilir.",
    borcama: "Ara ödemeyi kaydettikten sonra bankanın güncel planını yüklemek, kalan anapara ve toplam ödeme bilgilerinin doğru kalmasını sağlar.",
    related: ["erken-odeme", "kalan-anapara", "vade"],
  },
  {
    slug: "kredi-tahsis-ucreti",
    title: "Kredi tahsis ücreti",
    category: "Faiz ve maliyet",
    definition: "Bankanın kredi kullandırma sürecinde mevzuat ve sözleşme sınırları içinde talep edebildiği ücret kalemidir.",
    detail: "Tahsis ücreti faiz oranından ayrı bir maliyettir ve kredinin eline geçen net tutarı etkileyebilir. Kredi tekliflerini karşılaştırırken aylık taksitle birlikte toplam geri ödeme, efektif maliyet ve bütün zorunlu ücretler incelenmelidir.",
    example: "100.000 TL kredi onaylanıp tahsis ücreti kesilirse hesabına geçen net tutar 100.000 TL'den düşük olabilir; borç planındaki anapara yine sözleşmedeki tutara dayanır.",
    borcama: "Borcama kredi kaydında taksit ve kalan toplamı izler; kesin ücret tutarı için bankanın sözleşme ve ödeme planındaki satırları esas alır.",
    related: ["efektif-faiz-orani", "toplam-geri-odeme", "bsmv"],
  },
  {
    slug: "ihtiyac-kredisi",
    title: "İhtiyaç kredisi",
    category: "Kredi",
    definition: "Bireysel tüketicinin mal veya hizmet dışındaki kişisel nakit ihtiyacı için kullandığı tüketici kredisi türüdür.",
    detail: "İhtiyaç kredisinin aylık taksiti; anapara, vade, faiz ve ilgili maliyetlere göre oluşur. Teklif karşılaştırırken yalnızca aylık oranı değil, toplam geri ödemeyi ve erken ödeme koşullarını da görmek gerekir.",
    example: "120.000 TL ihtiyaç kredisi 24 ay vadeye yayıldığında her taksit anapara ve finansman maliyetinin belirli bir bölümünü içerir.",
    borcama: "İhtiyaç kredisini ödeme günü, taksit ve kalan planıyla kaydedebilir; diğer kart ve kredilerle aynı aylık tabloda takip edebilirsin.",
    related: ["aylik-taksit", "vade", "toplam-geri-odeme"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "sabit-faiz",
    title: "Sabit faiz",
    category: "Faiz ve maliyet",
    definition: "Sözleşmede belirlenen faiz oranının tanımlı dönem boyunca değişmeden uygulanmasıdır.",
    detail: "Sabit faiz, piyasa oranları değişse bile sözleşmedeki oranı korumayı amaçlar. Taksitin sabit olmasıyla aynı kavram değildir; vergi, ücret, ödeme yapısı veya gecikme gibi diğer unsurlar toplam maliyeti etkileyebilir.",
    example: "Aylık yüzde 3 sabit oranlı bir kredide piyasa oranı yükselse de sözleşmedeki normal faiz oranı aynı kalabilir.",
    borcama: "Kredi kaydına bankanın bildirdiği oranı girdiğinde hesaplar bu oranı kullanır; ödeme planındaki kesin taksit her zaman önceliklidir.",
    related: ["degisken-faiz", "faiz", "efektif-faiz-orani"],
  },
  {
    slug: "degisken-faiz",
    title: "Değişken faiz",
    category: "Faiz ve maliyet",
    definition: "Sözleşmede belirtilen referans veya kurala göre belirli dönemlerde değişebilen faiz oranıdır.",
    detail: "Değişken faizli üründe gelecekteki maliyet başlangıçtaki oranla sabit kalmayabilir. Güncelleme sıklığı, kullanılan referans ve uygulanabilecek sınırlar sözleşmede yer almalıdır; yeni oran taksit veya vadeyi etkileyebilir.",
    example: "Referans oran üç ayda bir güncelleniyorsa kredi taksiti veya faiz yükü her güncelleme döneminde yeniden hesaplanabilir.",
    borcama: "Oran değiştiğinde kredi bilgilerini veya ödeme planını güncellemek gerekir; eski oranla yapılan tahmin gelecekteki taksitleri kesin göstermez.",
    related: ["sabit-faiz", "faiz", "efektif-faiz-orani"],
  },
  {
    slug: "kart-limiti",
    title: "Kredi kartı limiti",
    category: "Kredi kartı",
    definition: "Kartla yapılabilecek işlemler için banka tarafından tanımlanan toplam üst sınırdır.",
    detail: "Kart limiti borç tutarı değildir. Kullanılabilir limit; mevcut borç, bekleyen provizyonlar, taksitli işlemler ve yapılan ödemelerle değişir. Birden fazla kartın toplam limiti de banka değerlendirmelerinde birlikte ele alınabilir.",
    example: "100.000 TL kart limitin ve 35.000 TL kullanılan tutarın varsa diğer bekleyen işlemler hariç kullanılabilir limitin yaklaşık 65.000 TL olabilir.",
    borcama: "Kart limitini dönem borcundan ayrı kaydetmek, asgari ödeme hesabında ve kartın güncel yükünü okurken iki rakamın karışmasını önler.",
    related: ["kullanilabilir-limit", "donem-borcu", "provizyon"],
    tool: "kredi-karti-asgari-odeme-hesaplayici",
  },
  {
    slug: "kullanilabilir-limit",
    title: "Kullanılabilir limit",
    category: "Kredi kartı",
    definition: "Kredi kartı toplam limitinin, mevcut ve bekleyen kullanımlar sonrasında işlem yapılabilir kalan bölümüdür.",
    detail: "Kullanılabilir limit her zaman toplam limit eksi dönem borcu kadar değildir. Ekstre sonrası harcamalar, provizyondaki işlemler, taksitlerin bloke edilen kısmı ve henüz karta yansımayan ödemeler rakamı değiştirebilir.",
    example: "50.000 TL limit ve 20.000 TL dönem borcu varken 5.000 TL bekleyen provizyon varsa kullanılabilir limit 30.000 TL'den düşük görünebilir.",
    borcama: "Borcama borç ve limit bilgisini ayrı tutar; kesin kullanılabilir limit için bankanın anlık kart ekranı esas alınır.",
    related: ["kart-limiti", "provizyon", "donem-borcu"],
  },
  {
    slug: "provizyon",
    title: "Provizyon",
    category: "Kredi kartı",
    definition: "Kart işleminin banka tarafından kontrol edilip kesin kayda dönüşmeden önce bekletildiği onay aşamasıdır.",
    detail: "Provizyondaki işlem kullanılabilir limiti azaltabilir fakat henüz ekstreye kesin işlem olarak yansımamış olabilir. İptal, tutar değişikliği veya işyerinin işlemi tamamlaması sonucunda provizyon kayda dönüşebilir ya da düşebilir.",
    example: "Otelde 4.000 TL provizyon alınması limiti geçici azaltabilir; kesinleşen tutar daha sonra farklı bir rakamla karta yansıyabilir.",
    borcama: "Ekstreye kesinleşmemiş provizyonu harcama olarak iki kez kaydetmemek için banka ekstresindeki muhasebeleşmiş işlemleri esas alır.",
    related: ["kullanilabilir-limit", "kredi-karti-ekstresi", "hesap-kesim-tarihi"],
  },
  {
    slug: "nakit-avans",
    title: "Nakit avans",
    category: "Kredi kartı",
    definition: "Kredi kartı limitinin belirli bir bölümünün nakit olarak kullanılmasıdır.",
    detail: "Nakit avans, alışveriş işleminden farklı faiz, ücret ve vergi koşullarına tabi olabilir. Maliyet başlangıç tarihi ve geri ödeme biçimi bankanın ürün koşullarında belirtilir; yalnız çekilen ana paraya bakmak toplam yükü göstermez.",
    example: "10.000 TL nakit avans kullandığında geri ödeme; çekilen tutara ek olarak işlem tarihinden itibaren oluşan maliyetleri içerebilir.",
    borcama: "Nakit avansı kart borcunun içinde takip edebilirsin; doğru maliyet için bankanın ekstre ve sözleşmesindeki oranları kullanmalısın.",
    related: ["taksitli-nakit-avans", "akdi-faiz", "kart-limiti"],
  },
  {
    slug: "taksitli-nakit-avans",
    title: "Taksitli nakit avans",
    category: "Kredi kartı",
    definition: "Kredi kartından kullanılan nakdin belirlenen vade ve taksitlerle geri ödendiği finansman işlemidir.",
    detail: "Taksitli nakit avans kart limitini etkiler ve alışveriş taksitinden farklı maliyetlere sahip olabilir. Aylık taksit düşük görünse bile toplam geri ödeme, faiz, vergi ve varsa ücretlerle birlikte karşılaştırılmalıdır.",
    example: "12.000 TL tutarın üç taksitte ödenmesi, her ay yalnız 4.000 TL anapara ödeneceği anlamına gelmeyebilir; taksit maliyet içerir.",
    borcama: "Düzenli taksit tutarını ve ödeme gününü aylık plana ekleyebilir; kartın toplam borcuyla çifte sayılmadığını kontrol edebilirsin.",
    related: ["nakit-avans", "aylik-taksit", "efektif-faiz-orani"],
  },
  {
    slug: "muacceliyet",
    title: "Muacceliyet",
    category: "Borç yönetimi",
    definition: "Bir borcun ödeme zamanının gelmiş ve alacaklı tarafından talep edilebilir hale gelmiş olmasıdır.",
    detail: "Muaccel borç, vadesi gelmiş borçtur; temerrüt ise bu yükümlülüğün zamanında yerine getirilmemesiyle ilişkilidir. Bazı sözleşmeler belirli ihlallerde kalan borcun tamamının muaccel olabileceğine dair hükümler içerebilir.",
    example: "Aylık taksidin ödeme günü geldiğinde o taksit muaccel olur. Sözleşmedeki koşullar oluşmadan bütün kalan taksitler otomatik olarak aynı anlama gelmez.",
    borcama: "Ödeme gününü ve kalan taksitleri gösterir; bir borcun hukuken tamamen muaccel olup olmadığını banka bildirimi veya sözleşme olmadan belirlemez.",
    related: ["temerrut", "son-odeme-tarihi", "tasfiye"],
  },
  {
    slug: "takipteki-alacak",
    title: "Takipteki alacak",
    category: "Borç yönetimi",
    definition: "Geri ödemesinde sorun oluştuğu için finansal kuruluşun özel izleme veya yasal takip sürecine aldığı alacaktır.",
    detail: "Bir borcun takipte sınıflandırılması yalnızca tek bir gecikme gününe bakılarak kullanıcı tarafından kesinleştirilemez. Bankanın bildirimi, ürünün sözleşmesi, düzenleyici sınıflandırmalar ve yürütülen süreç birlikte değerlendirilmelidir.",
    example: "Ödemesi geciken kredi için bankadan takip veya yasal süreç bildirimi geldiyse güncel bakiye ve ödeme seçenekleri doğrudan bankadan doğrulanmalıdır.",
    borcama: "Borcama ödeme geçmişini ve kalan tutarı takip eder; resmî takip statüsü ya da hukuki sonuç üretmez.",
    related: ["temerrut", "tasfiye", "borc-yapilandirma"],
  },
  {
    slug: "ibra",
    title: "İbra",
    category: "Borç yönetimi",
    definition: "Alacaklının belirli bir borç veya yükümlülük bakımından borçluyu tamamen ya da kısmen serbest bırakmasıdır.",
    detail: "İbra, yalnızca uygulamadaki bakiyenin sıfır görünmesiyle varsayılamaz. Kapsamı, şartları ve hangi borcu sona erdirdiği belgeye göre değişebilir; hukuki sonuç için yazılı banka veya alacaklı kaydı esas alınmalıdır.",
    example: "Borç ödendikten sonra verilen kapama veya ibra belgesi, hangi hesabın hangi tarih itibarıyla sonuçlandığını açıkça göstermelidir.",
    borcama: "Bir borcu kapalı olarak izlemen finansal planı günceller; resmî ibra yerine geçmez ve belgeyi bankandan veya alacaklıdan almalısın.",
    related: ["tasfiye", "borc-yapilandirma", "toplam-geri-odeme"],
  },
  {
    slug: "likidite",
    title: "Likidite",
    category: "Bütçe",
    definition: "Bir varlığın önemli değer kaybı yaşamadan ne kadar hızlı ve kolay nakde çevrilebildiğini anlatan ölçüdür.",
    detail: "Nakit yüksek likiditeye sahipken gayrimenkulün satılması zaman alabilir ve fiyat belirsizliği taşıyabilir. Bu nedenle toplam varlık yüksek olsa bile yaklaşan ödemeleri karşılayacak likit kaynak yetersiz olabilir.",
    example: "Evinin değeri borcundan yüksek olabilir; fakat yarınki kredi taksidini ödemek için hesabındaki nakit ve kolay erişilen birikim önemlidir.",
    borcama: "Varlık türlerini ayrı gösterir ve gayrimenkul gibi kolayca kullanılamayan değerleri hazır nakitmiş gibi borç ödemesine saymaz.",
    related: ["likit-varlik", "nakit-akisi", "net-varlik"],
  },
  {
    slug: "likit-varlik",
    title: "Likit varlık",
    category: "Bütçe",
    definition: "Kısa sürede, düşük işlem maliyeti ve sınırlı değer kaybıyla nakde çevrilebilen varlıktır.",
    detail: "Nakit ve vadesiz hesap bakiyesi en likit örneklerdendir; diğer varlıkların likiditesi erişim süresi ve satış koşuluna bağlıdır. Likit varlık toplam servetten farklı olarak yakın vadeli ödeme gücünü gösterir.",
    example: "20.000 TL nakit ve 300.000 TL değerinde araç sahibiysen toplam varlığın 320.000 TL olabilir; ancak hemen erişilebilir tutarın 20.000 TL'dir.",
    borcama: "Nakit, mevduat, araç ve gayrimenkulü ayrı türlerde tutarak borca karşı hemen kullanılabilecek kaynak ile toplam varlığı ayırır.",
    related: ["likidite", "net-varlik", "acil-durum-fonu"],
  },
  {
    slug: "acil-durum-fonu",
    title: "Acil durum fonu",
    category: "Bütçe",
    definition: "Beklenmeyen gider veya gelir kesintilerinde kullanılmak üzere ayrılan, kolay erişilebilir güvenlik birikimidir.",
    detail: "Acil durum fonunun hedefi herkes için aynı değildir; düzenli zorunlu giderler, gelir güvencesi, borç yapısı ve bakmakla yükümlü olunan kişiler dikkate alınır. Fon, günlük harcama hesabından ayrı tutulduğunda daha izlenebilir olur.",
    example: "Aylık zorunlu giderlerin 25.000 TL ise hedefini soyut bir toplam yerine kaç aylık temel gideri karşılayacağı üzerinden değerlendirebilirsin.",
    borcama: "Nakit ve birikimini borçlardan ayrı izleyerek acil durumda kullanılabilecek tutarın toplam finansal tablodaki yerini görebilirsin.",
    related: ["likit-varlik", "sabit-gider", "nakit-akisi"],
  },
  {
    slug: "sabit-gider",
    title: "Sabit gider",
    category: "Bütçe",
    definition: "Düzenli aralıklarla tekrarlanan ve kısa vadede tutarı ya da ödeme zorunluluğu kolay değişmeyen giderdir.",
    detail: "Kira, abonelik veya kredi taksiti sabit gider olabilir; ancak tutarın her ay tamamen aynı olması şart değildir. Bütçe planında önce zorunlu ve düzenli kalemler ayrılır, sonra değişken harcamalara alan bırakılır.",
    example: "Kira 18.000 TL ve kredi taksiti 7.000 TL ise yalnız bu iki kalem aylık 25.000 TL düzenli yük oluşturur.",
    borcama: "Sabit giderler her ay plana otomatik gelir; kredi ve yapılandırma taksitleri ikinci kez sayılmadan aynı aylık yükte gösterilir.",
    related: ["degisken-gider", "kullanilabilir-gelir", "butce-acigi"],
  },
  {
    slug: "degisken-gider",
    title: "Değişken gider",
    category: "Bütçe",
    definition: "Tutarı kullanım, tercih veya döneme göre değişen ve her ay aynı seviyede gerçekleşmeyen giderdir.",
    detail: "Market, ulaşım veya sosyal harcamalar değişken gider olabilir. Tamamen keyfî oldukları varsayılmamalıdır; bir bölümü temel ihtiyaçtır fakat tutarı yönetilebilir. Geçmiş aylar plan için daha gerçekçi bir ortalama sağlar.",
    example: "Market harcaman bir ay 8.000 TL, sonraki ay 10.500 TL olabilir; bütçede tek iyi aya değil birkaç aylık eğilime bakmak daha sağlıklıdır.",
    borcama: "Ekstre harcamalarını kategoriye ayırarak değişken giderlerin hangi kalemde büyüdüğünü ve aylık açığa etkisini görebilirsin.",
    related: ["sabit-gider", "nakit-akisi", "butce-acigi"],
  },
  {
    slug: "kullanilabilir-gelir",
    title: "Kullanılabilir gelir",
    category: "Bütçe",
    definition: "Gelirden zorunlu kesintiler ve temel yükümlülükler ayrıldıktan sonra planlama için kullanılabilen tutardır.",
    detail: "Kavramın kapsamı yapılan hesaba göre değişebilir; kişisel bütçede Borcama, kayıtlı gelirden zorunlu ödemeler ve yaşam giderleri çıktıktan sonra kalan alanı gösterir. Banka değerlendirmeleri farklı tanımlar kullanabilir.",
    example: "50.000 TL gelirden 20.000 TL zorunlu ödeme ve 18.000 TL yaşam gideri çıkıyorsa planında yaklaşık 12.000 TL alan kalır.",
    borcama: "Aylık tabloda gelir, borç ödemeleri ve harcamaları birlikte değerlendirerek fazla veya açık tutarını görünür hale getirir.",
    related: ["borc-gelir-orani", "butce-acigi", "nakit-akisi"],
  },
  {
    slug: "borc-gelir-orani",
    title: "Borç/gelir oranı",
    category: "Borç yönetimi",
    definition: "Düzenli borç ödemelerinin gelire oranını gösteren ve ödeme yükünü karşılaştırmak için kullanılan göstergedir.",
    detail: "Hesaba hangi borçların ve hangi gelir türünün katıldığı sonucu değiştirir. Tek başına kredi kararı veya mali sağlık hükmü vermez; yaşam giderleri, gelir istikrarı, faiz ve toplam borç ayrıca değerlendirilmelidir.",
    example: "Aylık borç ödemelerin 15.000 TL ve düzenli gelirin 50.000 TL ise basit borç/gelir oranı yüzde 30'dur.",
    borcama: "Kredi, kart ve ek hesap yükünü gelir tablonla birlikte gösterir; oranı tek başına güvenli veya riskli etiketi olarak kullanmaz.",
    related: ["kullanilabilir-gelir", "borc-kapatma-plani", "aylik-taksit"],
  },
  {
    slug: "mevduat-faizi",
    title: "Mevduat faizi",
    category: "Birikim",
    definition: "Bankada belirli koşullarla tutulan paraya, vade ve oran üzerinden ödenen brüt getiridir.",
    detail: "Bankanın ilan ettiği mevduat oranı genellikle yıllık brüt orandır. Gerçek net kazanç; ana para, vade günü, faiz oranı, stopaj ve ürün koşullarına bağlıdır. Kampanya oranının süresi ayrıca kontrol edilmelidir.",
    example: "100.000 TL'yi 32 gün vadede değerlendirdiğinde yıllık oran yalnızca 32 güne düşen brüt getiriyi üretir; stopaj sonrası net tutar daha düşük olur.",
    borcama: "Mevduat hesaplayıcıda bankanın verdiği yıllık oran, vade ve stopajla net getiriyi görebilir; birikimini diğer varlıklarınla izleyebilirsin.",
    related: ["faiz", "stopaj", "vade"],
    tool: "mevduat-faizi-hesaplama",
  },
  {
    slug: "stopaj",
    title: "Stopaj",
    category: "Birikim",
    definition: "Verginin gelir sahibine ödenmeden önce kaynağında kesilip ilgili idareye aktarılması yöntemidir.",
    detail: "Mevduatta stopaj, brüt faiz getirisi üzerinden kesilen verginin net kazanca etkisini gösterir. Oran ürün türü, vade, açılış veya yenileme tarihi ve güncel mevzuata göre değişebileceği için bankanın bildirdiği oran kullanılmalıdır.",
    example: "Brüt faiz kazancı 5.000 TL ise stopaj bu kazanç üzerinden hesaplanır; ana para üzerinden aynı biçimde kesinti yapıldığı varsayılmaz.",
    borcama: "Mevduat hesaplayıcıya bankanın güncel stopaj oranını girdiğinde brüt faiz, kesinti ve net getiri ayrı gösterilir.",
    related: ["mevduat-faizi", "faiz", "vade"],
    tool: "mevduat-faizi-hesaplama",
  },
  {
    slug: "bilesik-faiz",
    title: "Bileşik faiz",
    category: "Faiz ve maliyet",
    definition: "Her dönemin faizinin anaparaya eklenip sonraki dönemde yeni toplam üzerinden faiz hesaplanmasıdır.",
    detail: "Bileşik etki, faiz veya getirinin dönem sonunda anaparaya eklenmesi ve yeniden işleme girmesiyle oluşur. Basit yıllık oranla aynı sonucu vermez; dönem sıklığı ve toplam süre fark büyüklüğünü belirler.",
    example: "100.000 TL'ye ilk dönem yüzde 2 getiri eklenirse sonraki dönem hesap 102.000 TL üzerinden devam eder; ikinci dönemin getirisi yalnız ilk anaparaya uygulanmaz.",
    borcama: "Hesaplama araçları ürünün gerçek ödeme veya yenileme düzenini kullanır; bileşik etki varsayılıyorsa sonuç açıklamasında dönem koşulları ayrıca belirtilir.",
    related: ["faiz", "efektif-faiz-orani", "mevduat-faizi"],
  },
  {
    slug: "borc",
    title: "Borç",
    category: "Borç yönetimi",
    definition: "Bir kişi veya kurumun başka bir tarafa para, mal ya da hizmet ödeme yükümlülüğüdür.",
    detail: "Borç yalnız kullanılan ana paradan ibaret olmayabilir; faiz, vergi, ücret ve vade koşulları toplam yükü değiştirir. Sağlıklı bir karşılaştırmada güncel bakiye, aylık ödeme, son ödeme tarihi ve toplam geri ödeme birlikte ele alınır.",
    example: "50.000 TL ihtiyaç kredisi kullanan kişinin anapara borcu 50.000 TL olsa da vade boyunca ödeyeceği toplam tutar faiz ve ücretlerle daha yüksek olabilir.",
    borcama: "Kart, kredi ve ek hesaplarını tek tabloda ayrı borç türleri olarak izleyebilir; kalan tutarı, ödeme gününü ve aylık yükü birlikte görebilirsin.",
    related: ["anapara", "toplam-geri-odeme", "borc-kapatma-plani"],
  },
  {
    slug: "alacak",
    title: "Alacak",
    category: "Borç yönetimi",
    definition: "Bir kişi veya kurumun başka bir taraftan para, mal ya da hizmet isteme hakkını ifade eder.",
    detail: "Aynı mali ilişki borçlu açısından borç, alacaklı açısından alacaktır. Alacağın vadesi, teminatı, tahsil edilme ihtimali ve gecikme durumu değerini etkileyebilir; kayıtlı tutar her zaman tahsil edilmiş nakit anlamına gelmez.",
    example: "Bir arkadaşına verdiğin 5.000 TL geri ödenene kadar senin için alacak, parayı alan kişi için borç niteliğindedir.",
    borcama: "Borcama ağırlıklı olarak kendi borç ve varlık tablonu izler; beklenen bir tahsilatı gerçekleşmeden kesin gelir gibi değerlendirmemek bütçeni daha gerçekçi tutar.",
    related: ["borc", "vade", "nakit-akisi"],
  },
  {
    slug: "kredi-notu",
    title: "Kredi notu",
    category: "Kredi",
    definition: "Finansal geçmişe dayalı verilerle kişinin kredi geri ödeme riskini özetlemek için üretilen puandır.",
    detail: "Kredi notu tek başına kredi onayı anlamına gelmez. Bankalar gelir, mevcut borç, ödeme geçmişi, çalışma durumu, teminat ve kendi risk politikalarıyla birlikte değerlendirme yapar; kullanılan puan aralığı kuruma göre değişebilir.",
    example: "Düzenli ödeme geçmişi kredi değerlendirmesini destekleyebilir; fakat yüksek mevcut borç yükü nedeniyle yeni kredi başvurusu yine reddedilebilir.",
    borcama: "Borcama kredi notunu hesaplamaz; borçlarını ve ödeme günlerini düzenli izlemen, gecikme riskini erken fark etmene yardımcı olur.",
    related: ["risk-raporu", "borc-gelir-orani", "gecikme-faizi"],
  },
  {
    slug: "risk-raporu",
    title: "Risk raporu",
    category: "Kredi",
    definition: "Kişinin bankalardaki kredi, kredi kartı ve benzeri borç ilişkilerini toplu biçimde gösteren rapordur.",
    detail: "Risk raporunda limit, borç, ödeme performansı veya gecikme bilgileri yer alabilir. Rapor mevcut finansal yükü anlamaya yardım eder ancak kredi kararı değildir; içeriği sağlayıcıya ve rapor tarihine göre değişebilir.",
    example: "Farklı bankalardaki kart ve kredi bakiyelerini tek tek hatırlamak yerine risk raporundan kontrol edip kendi kayıtlarınla karşılaştırabilirsin.",
    borcama: "Risk raporundaki güncel borçları Borcama'ya kaydederek ödeme planını kurabilir; resmî rapor ile kişisel takip tablonu birbirinden ayrı tutabilirsin.",
    related: ["kredi-notu", "borc", "kart-limiti"],
  },
  {
    slug: "konut-kredisi",
    title: "Konut kredisi",
    category: "Kredi",
    definition: "Konut satın alımını finanse etmek için kullanılan ve çoğunlukla taşınmaz teminatlı uzun vadeli kredidir.",
    detail: "Konut kredisinde faiz veya kâr payı, vade, ekspertiz, sigorta, tahsis ücreti ve erken ödeme koşulları toplam maliyeti etkiler. Aylık taksidin uygun görünmesi, uzun vadedeki toplam geri ödemenin düşük olduğu anlamına gelmez.",
    example: "120 ay vadeli bir konut kredisinde aylık taksit bütçeye uyabilir; yine de toplam geri ödeme kullanılan anaparanın birkaç katına çıkabilir.",
    borcama: "Ödeme planını yükleyerek kalan taksit, kalan toplam ödeme ve aylık yükü diğer borçlarınla aynı tabloda takip edebilirsin.",
    related: ["ipotek", "toplam-geri-odeme", "erken-odeme"],
  },
  {
    slug: "tasit-kredisi",
    title: "Taşıt kredisi",
    category: "Kredi",
    definition: "Yeni veya ikinci el araç alımını finanse etmek amacıyla kullanılan tüketici kredisi türüdür.",
    detail: "Taşıt kredilerinde araç değeri, kredi oranı, vade, faiz, sigorta ve teminat koşulları önemlidir. Aracın zamanla değer kaybetmesi ile kalan kredi borcunun seyri aynı olmayabilir.",
    example: "Araç değeri ilk yıllarda hızlı düşerken kredi bakiyesi daha yavaş azalırsa, aracı satmak borcun tamamını kapatmaya yetmeyebilir.",
    borcama: "Taşıt kredisinin ödeme planını izlerken aracı varlık olarak ayrı kaydedebilir ve borç ile varlık değerini net durumda birlikte görebilirsin.",
    related: ["rehin", "kalan-anapara", "net-varlik"],
  },
  {
    slug: "kredi-hayat-sigortasi",
    title: "Kredi hayat sigortası",
    category: "Kredi",
    definition: "Kredi borçlusunun yaşamına ilişkin belirli risklerde poliçe koşulları kapsamında teminat sağlayan sigortadır.",
    detail: "Teminat kapsamı, istisnalar, süre, prim ve lehtar bilgileri poliçede belirlenir. Sigortanın bulunması her durumda bütün borcun ödeneceği anlamına gelmez; kredi sözleşmesi ve poliçe birlikte incelenmelidir.",
    example: "Kredi açılışında tek seferde kesilen veya taksitlere yansıtılan sigorta primi, kredinin faiz dışındaki toplam maliyetini artırabilir.",
    borcama: "Kredi takibini toplam geri ödeme üzerinden yaparken sigorta ve diğer masrafları banka ödeme planındaki tutarlarla karşılaştırabilirsin.",
    related: ["ihtiyac-kredisi", "toplam-geri-odeme", "kredi-tahsis-ucreti"],
  },
  {
    slug: "ipotek",
    title: "İpotek",
    category: "Borç ve hukuk",
    definition: "Bir alacağı güvence altına almak için taşınmaz üzerinde kurulan ve tapuya tescil edilen teminattır.",
    detail: "İpotek taşınmazın mülkiyetini kendiliğinden alacaklıya geçirmez; borcun ödenmemesi halinde kanuni takip yollarında güvence sağlar. Derece, tutar ve kaldırma koşulları resmî kayıtlardan kontrol edilmelidir.",
    example: "Konut kredisiyle alınan ev üzerine banka lehine ipotek konabilir; kredi kapandığında ipoteğin terkin işlemi ayrıca takip edilir.",
    borcama: "Konut kredisi bakiyesini ve ödeme planını izleyebilirsin; Borcama tapu kaydı tutmaz ve ipoteğin kaldırıldığını varsaymaz.",
    related: ["konut-kredisi", "rehin", "temerrut"],
  },
  {
    slug: "rehin",
    title: "Rehin",
    category: "Borç ve hukuk",
    definition: "Bir borcun ödenmesini güvenceye almak için taşınır mal veya hak üzerinde kurulan teminattır.",
    detail: "Rehnin konusu, kuruluş biçimi ve alacaklıya sağladığı haklar işleme göre değişir. Borcun kapanmasıyla ekonomik neden ortadan kalksa da ilgili kayıt veya kaldırma işleminin tamamlanması ayrıca gerekebilir.",
    example: "Taşıt kredisiyle alınan araç üzerinde banka lehine rehin bulunabilir; satış öncesinde borç ve rehin kaldırma süreci kontrol edilir.",
    borcama: "Taşıt kredisi ile araç değerini ayrı kaydedebilirsin; resmî rehin durumu için banka ve ilgili sicil kayıtları esas alınır.",
    related: ["tasit-kredisi", "ipotek", "borc"],
  },
  {
    slug: "kefil",
    title: "Kefil",
    category: "Borç ve hukuk",
    definition: "Borçlunun yükümlülüğünü yerine getirmemesi halinde belirli koşullarla sorumluluk üstlenen kişidir.",
    detail: "Kefilin sorumluluğu kefalet sözleşmesinin türüne, tutarına, süresine ve kanuni şartlara bağlıdır. Kefil olmak yalnız referans vermek değildir; kişinin kendi mali durumunu etkileyebilecek hukuki bir yükümlülük doğurabilir.",
    example: "Bir krediye kefil olan kişi, borçlu ödeme yapmadığında sözleşme ve kanun koşulları çerçevesinde ödeme talebiyle karşılaşabilir.",
    borcama: "Borcama kendi adına takip ettiğin borçları gösterir; kefalet kaynaklı olası yükümlülükler için sözleşme ve resmî bildirim ayrıca incelenmelidir.",
    related: ["kefalet", "borc", "muacceliyet"],
  },
  {
    slug: "kefalet",
    title: "Kefalet",
    category: "Borç ve hukuk",
    definition: "Kefilin, borçlunun borcunu yerine getirmemesi riskine karşı alacaklıya güvence verdiği sözleşme ilişkisidir.",
    detail: "Kefaletin geçerliliği ve kapsamı şekil şartlarına, azami tutara, tarihe ve kefalet türüne bağlı olabilir. Müteselsil kefalet ile adi kefaletin sonuçları aynı değildir; imzadan önce hukuki ve mali etkiler anlaşılmalıdır.",
    example: "Kredi sözleşmesindeki kefalet limiti yalnız ana parayı değil, şartlarına göre faiz ve masrafları da kapsayabilir.",
    borcama: "Kefalet ilişkisini otomatik borç saymaz; kesin sorumluluk doğduğunda tutarı ilgili borç kaydıyla planına dahil edebilirsin.",
    related: ["kefil", "temerrut", "alacak"],
  },
  {
    slug: "icra-takibi",
    title: "İcra takibi",
    category: "Borç ve hukuk",
    definition: "Alacaklının alacağını devletin icra organları aracılığıyla tahsil etmek için başlattığı hukuki süreçtir.",
    detail: "Takibin türü, borcun belgesine ve niteliğine göre değişebilir. Tebligat, itiraz ve ödeme süreleri hak kaybı yaratabileceğinden yalnız uygulama kaydına güvenilmemeli; resmî evrak ve gerektiğinde uzman desteği esas alınmalıdır.",
    example: "Ödenmeyen bir borç için ödeme emri tebliğ edildiğinde belgedeki süreler, dosya numarası ve talep edilen tutar dikkatle kontrol edilir.",
    borcama: "Gecikmiş borcu ve ödeme planını görünür tutar; icra dosyasının hukuki durumunu belirlemez veya resmî süreleri takip etmez.",
    related: ["odeme-emri", "haciz", "temerrut"],
  },
  {
    slug: "haciz",
    title: "Haciz",
    category: "Borç ve hukuk",
    definition: "Kesinleşen takipte alacağın tahsili amacıyla borçlunun belirli mal, hak veya alacaklarına hukuken el konulmasıdır.",
    detail: "Haczin kapsamı, uygulanabilecek mallar, itiraz yolları ve süreleri dosyanın niteliğine göre değişir. Her gecikmiş borç kendiliğinden haciz anlamına gelmez; resmî takip aşamaları ve kararlar önemlidir.",
    example: "Bir icra dosyasında banka hesabına bloke konulması ile yalnızca bankanın gecikme bildirimi göndermesi aynı hukuki aşama değildir.",
    borcama: "Borç bakiyeni planlamana yardım eder fakat haciz veya bloke durumunu doğrulamaz; bu bilgi resmî dosya ve kurum kayıtlarından kontrol edilmelidir.",
    related: ["icra-takibi", "odeme-emri", "tasfiye"],
  },
  {
    slug: "odeme-emri",
    title: "Ödeme emri",
    category: "Borç ve hukuk",
    definition: "İcra takibinde borçluya borcu ödemesi veya kanuni sürede ilgili hakkını kullanması için gönderilen resmî belgedir.",
    detail: "Ödeme emrindeki alacaklı, tutar, dosya numarası, tebliğ tarihi ve süreler önemlidir. Belgenin türüne göre itiraz veya ödeme usulü değişebilir; ekran görüntüsü ya da banka mesajı resmî tebligatla karıştırılmamalıdır.",
    example: "Belge tebliğ edildiğinde borcun sana ait olup olmadığını, talep edilen kalemleri ve işlem yapılabilecek son tarihi kontrol etmek gerekir.",
    borcama: "Borcama ödeme günlerini hatırlatır; resmî ödeme emrine cevap vermez ve hukuki süre hesabı yapmaz.",
    related: ["icra-takibi", "haciz", "alacak"],
  },
  {
    slug: "konkordato",
    title: "Konkordato",
    category: "Borç ve hukuk",
    definition: "Borçlarını vadesinde ödeyemeyen veya ödeyememe tehlikesi bulunan borçlunun alacaklılarla mahkeme denetiminde anlaşma sürecidir.",
    detail: "Konkordato basit bir borç yapılandırma başvurusu değildir; kanunda düzenlenen, mahkeme ve komiser denetimi içeren özel bir süreçtir. Geçici mühlet, kesin mühlet ve tasdik aşamalarının etkileri ayrı değerlendirilir.",
    example: "Bir şirketin bankayla kendi arasında vadeyi uzatması yapılandırma olabilir; mahkeme denetimli konkordato ile aynı işlem değildir.",
    borcama: "Kişisel borç planı oluşturur ancak konkordato uygunluğu veya hukuki sonucu hakkında karar vermez; resmî süreç için uzman görüşü gerekir.",
    related: ["borc-yapilandirma", "tasfiye", "alacak"],
  },
  {
    slug: "kart-aidati",
    title: "Kredi kartı aidatı",
    category: "Kredi kartı",
    definition: "Kredi kartının sunulması ve kullanımı karşılığında banka tarafından dönemsel olarak alınabilen ücrettir.",
    detail: "Aidatın tutarı, tahsil zamanı, muafiyet koşulları ve ücretsiz kart seçeneği bankanın sözleşmesine göre değişir. Ekstrede ayrı işlem olarak görünür ve dönem borcuna dahil olduğunda ödenmeyen tutarın maliyetini etkileyebilir.",
    example: "Yıllık kart aidatı ekstreye 900 TL olarak yansıdığında, o ayki dönem borcu alışveriş harcamalarından 900 TL daha yüksek görünür.",
    borcama: "Ekstre içe aktarımında aidatı ayrı gider olarak görebilir; kartın yıllık maliyetini harcamalardan ayırarak değerlendirebilirsin.",
    related: ["kredi-karti-ekstresi", "donem-borcu", "toplam-geri-odeme"],
  },
  {
    slug: "taksit",
    title: "Taksit",
    category: "Kredi",
    definition: "Bir borcun belirli aralıklarla ödenmek üzere bölünmüş her bir ödeme parçasıdır.",
    detail: "Taksit tutarı anapara, faiz, vergi veya ürün koşuluna göre diğer kalemleri içerebilir. Eşit taksitli planda ödeme aynı görünse de her taksitte anapara ve faiz dağılımı farklı olabilir.",
    example: "12 ay vadeli bir kredide her ay 5.000 TL ödenmesi toplam 60.000 TL nakit çıkışı yaratır; bunun tamamı anapara değildir.",
    borcama: "Aylık taksit, kalan taksit sayısı ve ödeme gününü ayrı alanlarda göstererek kredinin takvimini okunur hale getirir.",
    related: ["aylik-taksit", "kalan-anapara", "toplam-geri-odeme"],
  },
  {
    slug: "taksitlendirme",
    title: "Taksitlendirme",
    category: "Kredi kartı",
    definition: "Tek bir borç veya harcamanın birden fazla vadeli ödemeye bölünmesi işlemidir.",
    detail: "İşlem anında taksit, sonradan taksitlendirme ve ekstre taksitlendirme farklı ürünlerdir. Faiz, ücret, erken kapama ve kart limitine etkileri değişebilir; yalnız aylık taksite bakmak toplam maliyeti gizleyebilir.",
    example: "18.000 TL harcamayı altı taksite bölmek aylık ödemeyi düşürür; banka ayrıca ücret veya faiz uygularsa toplam geri ödeme 18.000 TL'yi aşar.",
    borcama: "Taksitli harcamaları kalan aylarıyla izleyebilir ve aynı ayda kredi kartına binecek toplam taksit yükünü görebilirsin.",
    related: ["taksit", "donem-borcu", "efektif-faiz-orani"],
  },
  {
    slug: "brut-gelir",
    title: "Brüt gelir",
    category: "Bütçe",
    definition: "Vergi, prim ve diğer zorunlu kesintiler yapılmadan önce hesaplanan toplam gelir tutarıdır.",
    detail: "Brüt gelir maaş bordrosunda veya ticari faaliyette farklı kalemlerden oluşabilir. Harcanabilir tutarı doğrudan göstermez; bütçe yapılırken hesaba gerçekten geçen net gelir ve düzenli olmayan ödemeler ayrıştırılmalıdır.",
    example: "Aylık brüt ücret 70.000 TL olsa da vergi ve prim kesintilerinden sonra banka hesabına daha düşük bir net tutar geçebilir.",
    borcama: "Aylık plan için hesaba fiilen geçen net geliri kaydetmek daha gerçekçi sonuç verir; brüt tutarı gelir gibi kullanmak sahte bir fazla oluşturabilir.",
    related: ["net-gelir", "kullanilabilir-gelir", "nakit-akisi"],
  },
  {
    slug: "net-gelir",
    title: "Net gelir",
    category: "Bütçe",
    definition: "Vergi, prim ve benzeri kesintiler sonrasında kişinin eline geçen gelir tutarıdır.",
    detail: "Net gelir bütçenin başlangıç noktasıdır; ancak bunun tamamı serbestçe harcanabilir değildir. Kira, faturalar, borç taksitleri ve temel yaşam giderleri çıktıktan sonra kullanılabilir alan bulunur.",
    example: "Bordroda brüt 70.000 TL görünen ücretin hesaba geçen kısmı 53.000 TL ise aylık bütçe 70.000 TL üzerinden kurulmamalıdır.",
    borcama: "Düzenli net gelirini kaydederek borç ödemeleri ve yaşam giderlerinden sonra ay sonunda ne kadar alan kaldığını görebilirsin.",
    related: ["brut-gelir", "kullanilabilir-gelir", "borc-gelir-orani"],
  },
  {
    slug: "tasarruf-orani",
    title: "Tasarruf oranı",
    category: "Birikim",
    definition: "Belirli bir dönemde gelirin harcanmayıp birikime ayrılan bölümünün gelire oranıdır.",
    detail: "Oranı hesaplarken kullanılan gelir ve tasarruf tanımı açık olmalıdır. Borç anaparası ödemesi bazı analizlerde servet artışı sayılabilir; günlük bütçede ise nakit çıkışı olduğu için ayrı izlenmesi daha anlaşılırdır.",
    example: "Aylık net gelir 50.000 TL ve düzenli birikim 5.000 TL ise basit tasarruf oranı yüzde 10'dur.",
    borcama: "Gelir, gider, borç ödemesi ve varlık artışını ayrı izleyerek gerçekten birikime ayırdığın tutarı aylık nakit fazlasıyla karıştırmadan görebilirsin.",
    related: ["net-gelir", "acil-durum-fonu", "net-varlik"],
  },
  {
    slug: "enflasyon",
    title: "Enflasyon",
    category: "Birikim",
    definition: "Mal ve hizmetlerin genel fiyat düzeyinin zaman içinde sürekli artması ve paranın satın alma gücünün azalmasıdır.",
    detail: "Tek bir ürünün fiyat artışı enflasyon değildir; genel bir sepetin zaman içindeki değişimi ölçülür. Kişisel harcama sepeti resmî endeksten farklı olduğu için herkesin hissettiği fiyat artışı aynı olmayabilir.",
    example: "Gelirin yüzde 20 artarken düzenli harcamaların yüzde 30 artarsa nominal olarak daha çok kazansan bile bütçedeki gerçek alan daralabilir.",
    borcama: "Aylık giderlerini geçmiş dönemlerle karşılaştırarak kendi harcama eğilimini görürsün; Borcama resmî enflasyon hesaplayıcısının yerine geçmez.",
    related: ["satin-alma-gucu", "reel-getiri", "nominal-getiri"],
  },
  {
    slug: "nominal-getiri",
    title: "Nominal getiri",
    category: "Birikim",
    definition: "Bir yatırım veya birikimin enflasyon etkisi çıkarılmadan para cinsinden gösterilen getirisidir.",
    detail: "Nominal getiri hesabın kaç lira veya yüzde büyüdüğünü anlatır; bu artışın satın alma gücünü ne kadar yükselttiğini göstermez. Vergi, ücret ve enflasyon düşüldüğünde gerçek sonuç farklı olabilir.",
    example: "Birikimin bir yılda yüzde 30 büyürken fiyatlar genel düzeyi yüzde 35 artarsa nominal kazanç vardır fakat satın alma gücü azalmış olabilir.",
    borcama: "Varlık değerindeki değişimi nominal tutarla izleyebilir; karar verirken vergi, maliyet ve enflasyon etkisini ayrıca değerlendirmen gerekir.",
    related: ["reel-getiri", "enflasyon", "mevduat-faizi"],
  },
  {
    slug: "reel-getiri",
    title: "Reel getiri",
    category: "Birikim",
    definition: "Bir yatırımın nominal getirisinden enflasyonun satın alma gücü üzerindeki etkisi arındırılarak bulunan getiridir.",
    detail: "Yaklaşık hesapta nominal oran ile enflasyon farkına bakılsa da doğru reel oran bileşik ilişkiyle hesaplanır. Vergi ve ücretler de yatırımcının elinde kalan gerçek sonucu ayrıca düşürebilir.",
    example: "Yüzde 40 nominal getiri ve yüzde 30 enflasyon olduğunda reel getiri basitçe yüzde 10 kabul edilmez; oranların bileşik ilişkisi kullanılır.",
    borcama: "Borcama varlık tutarını gösterir; reel getiri değerlendirmesinde güncel enflasyon, vergi ve ürün maliyetini ayrıca kontrol etmelisin.",
    related: ["nominal-getiri", "enflasyon", "satin-alma-gucu"],
  },
  {
    slug: "satin-alma-gucu",
    title: "Satın alma gücü",
    category: "Bütçe",
    definition: "Belirli miktardaki parayla satın alınabilen mal ve hizmet miktarını ifade eder.",
    detail: "Paranın üzerindeki nominal tutar aynı kalsa bile fiyatlar arttığında satın alma gücü düşer. Gelir artışı, birikim getirisi ve borç maliyeti değerlendirilirken yalnız lira tutarı değil gerçek alım kapasitesi de önemlidir.",
    example: "Geçen yıl 10.000 TL ile alınan sepet bu yıl 13.000 TL olduysa 10.000 TL'nin satın alma gücü azalmıştır.",
    borcama: "Aylık harcamalarını kategoriler halinde izleyerek aynı yaşam düzeninin zaman içindeki maliyet değişimini kendi verilerin üzerinden görebilirsin.",
    related: ["enflasyon", "reel-getiri", "net-gelir"],
  },
  {
    slug: "varlik",
    title: "Varlık",
    category: "Birikim",
    definition: "Ekonomik değeri bulunan ve kişiye gelecekte fayda sağlama potansiyeli taşıyan para, mal veya haktır.",
    detail: "Nakit, mevduat, yatırım, araç ve gayrimenkul varlık örnekleridir. Her varlığın değeri, likiditesi ve riski aynı değildir; borçla alınmış bir varlığın brüt değeri kişinin net servetini tek başına göstermez.",
    example: "1.000.000 TL değerindeki araç varlıktır; araç için 600.000 TL kredi borcu varsa net durum hesabında iki kalem birlikte ele alınır.",
    borcama: "Varlıkları türlerine göre kaydedip borçlarından ayrı izler; toplam varlık ile net varlık arasındaki farkı görünür kılar.",
    related: ["net-varlik", "likit-varlik", "yukumluluk"],
  },
  {
    slug: "yukumluluk",
    title: "Yükümlülük",
    category: "Borç yönetimi",
    definition: "Geçmiş bir işlem veya sözleşme nedeniyle gelecekte para ödeme ya da başka bir edimi yerine getirme sorumluluğudur.",
    detail: "Kredi, kart borcu, vergi veya sözleşmeden doğan ödeme yükümlülüğü finansal tabloda borç niteliği taşıyabilir. Kesinleşmiş borç ile yalnızca olası risk aynı şekilde değerlendirilmemelidir.",
    example: "Önümüzdeki 24 ay boyunca ödenecek kredi taksitleri gelecekteki nakit akışını etkileyen bir yükümlülüktür.",
    borcama: "Kayıtlı kredi, kart ve ek hesapları aylık ödeme yüküne dönüştürerek hangi tarihte ne kadar nakit çıkışı olacağını gösterir.",
    related: ["borc", "varlik", "nakit-akisi"],
  },
];

export const FINANSAL_SOZLUK_KATEGORILERI = [...new Set(FINANSAL_SOZLUK.map((terim) => terim.category))];

export function finansalSozlukTerimi(slug) {
  return FINANSAL_SOZLUK.find((terim) => terim.slug === slug);
}
