export const FINANSAL_SOZLUK_GUNCELLEME_TARIHI = "2026-09-23";

export const FINANSAL_SOZLUK = [
  {
    slug: "faiz",
    title: "Faiz",
    category: "Faiz ve maliyet",
    definition: "Paranın belirli bir süre kullanılmasının karşılığında ödenen veya kazanılan tutar ya da orandır.",
    detail: "Faiz tek bir kavram gibi görünse de borçta ve birikimde farklı sonuç üretir. Kredide maliyet, mevduatta getiri olabilir; nominal oran, efektif oran, akdi faiz ve gecikme faizi birbirinin yerine kullanılmamalıdır.",
    example: "100.000 TL borca aylık yüzde 3 oran uygulanması, vergi ve diğer maliyetler hariç ilk ay için yaklaşık 3.000 TL faiz anlamına gelebilir; kesin hesap ürün koşullarına bağlıdır.",
    borcama: "Borcama, kullanıcı oran girdiyse bu oranı; oran yoksa uygun ürün için güncel resmî referansı tahmin olarak kullanır ve faiz ile anaparayı ayrı gösterir.",
    related: ["akdi-faiz", "gecikme-faizi", "efektif-faiz-orani"],
    tool: "borc-kapatma-hesaplayici",
  },
  {
    slug: "temerrut",
    title: "Temerrüt",
    category: "Borç yönetimi",
    definition: "Bir borçlunun vadesi gelmiş yükümlülüğünü gereken zamanda ve koşullarda yerine getirmemesi durumudur.",
    detail: "Temerrüt yalnızca 'borcun bulunması' anlamına gelmez; ödeme yükümlülüğünün muaccel olması ve zamanında yerine getirilmemesiyle ilgilidir. Sonuçları sözleşmeye, borcun türüne ve mevzuata göre değişebileceğinden banka bildirimi veya hukuki belge esas alınmalıdır.",
    example: "Vadesi 15 Eylül olan bir taksit sözleşmede belirtilen süre ve koşullarda ödenmezse gecikme ve temerrüt hükümleri gündeme gelebilir.",
    borcama: "Yaklaşan ödeme günlerini aynı takvimde görmek, ödeme vadesi geçmeden eksik bütçeyi fark etmene yardımcı olur; Borcama hukuki durum tespiti yapmaz.",
    related: ["temerrut-faizi", "son-odeme-tarihi", "gecikme-faizi"],
    tool: "aylik-odeme-takvimi",
  },
  {
    slug: "temerrut-faizi",
    title: "Temerrüt faizi",
    category: "Faiz ve maliyet",
    definition: "Vadesinde yerine getirilmeyen para borcu için temerrüt döneminde uygulanabilen faizdir.",
    detail: "Temerrüt faizi ile normal sözleşme faizi aynı kavram değildir. Oranın kaynağı, hangi tutara uygulanacağı ve başlangıç tarihi borcun türüne, sözleşmeye ve güncel mevzuata göre değişebilir; banka veya alacaklı tarafından bildirilen hesap kontrol edilmelidir.",
    example: "Bir taksidin vadesi geçtiğinde hesaplanan ek maliyet, normal dönem faizinden farklı bir temerrüt kuralına dayanabilir.",
    borcama: "Borcama geciken tutarı ve ödeme tarihini görünür kılar; kesin temerrüt maliyetini banka belgesi olmadan kesinmiş gibi sunmaz.",
    related: ["temerrut", "gecikme-faizi", "akdi-faiz"],
  },
  {
    slug: "tasfiye",
    title: "Tasfiye",
    category: "Borç yönetimi",
    definition: "Bir hesap, borç, varlık veya kurumla ilgili mali ilişkilerin sonuçlandırılıp kapatılması sürecidir.",
    detail: "Finansal bağlama göre tasfiye; borcun kapatılması, bir varlığın nakde çevrilmesi veya bir kurumun alacak ve yükümlülüklerinin sonuçlandırılması anlamına gelebilir. Günlük aramalarda 'tasviye' diye de yazılsa da doğru yazım 'tasfiye'dir; işlemin hukuki sonucu ilgili belgeye göre değerlendirilir.",
    example: "Bir borcun tasfiye edilmesi, ödeme veya mutabakat sonunda borç ilişkisinin kapatılması anlamına gelebilir; yalnızca taksit sayısının bitmesi her durumda aynı hukuki sonucu göstermeyebilir.",
    borcama: "Borcama'da bir borcun kalan tutarı sıfırlandığında finansal takip tamamlanır; resmî kapanış ve ibra için banka ya da alacaklı belgesi esas alınır.",
    related: ["borc-yapilandirma", "kalan-anapara", "toplam-geri-odeme"],
  },
  {
    slug: "asgari-odeme",
    title: "Asgari ödeme",
    category: "Kredi kartı",
    definition: "Kredi kartı ekstresinde, son ödeme tarihine kadar ödenmesi gereken en düşük tutardır.",
    detail: "Asgari ödeme, kartın dönem borcunun tamamını kapatmaz. Yalnızca bankanın o ekstre için bildirdiği alt ödeme eşiğini gösterir; ödenmeyen bölüm sonraki döneme taşınır ve sözleşme ile güncel mevzuata göre maliyet doğurabilir.",
    example: "Dönem borcun 20.000 TL ve ekstredeki asgari ödeme 8.000 TL ise 8.000 TL ödemek kartı tamamen kapatmaz. Kalan 12.000 TL devreden bakiye olur.",
    borcama: "Borcama'da dönem borcu, asgari ödeme ve yaptığın ödeme ayrı tutulur; böylece yalnızca asgariyi ödediğinde geriye ne kaldığını görebilirsin.",
    related: ["donem-borcu", "devreden-bakiye", "akdi-faiz"],
    tool: "kredi-karti-asgari-odeme-hesaplayici",
  },
  {
    slug: "donem-borcu",
    title: "Dönem borcu",
    category: "Kredi kartı",
    definition: "Bir kredi kartı hesap kesim döneminde ekstreye yansıyan toplam borçtur.",
    detail: "Dönem borcu; o dönemde ekstreye giren alışveriş, taksit, nakit çekim, ücret, önceki dönemden taşınan tutar ve varsa maliyetlerden oluşabilir. Güncel borçla aynı şey değildir; hesap kesiminden sonra yaptığın yeni işlemler güncel borca eklenir ama ilgili ekstreye girmez.",
    example: "Ekstren 5 Eylül'de kesildiyse o tarihe kadar ekstreleşen 18.500 TL dönem borcudur. 6 Eylül'deki yeni harcama bir sonraki döneme kalabilir.",
    borcama: "Kart eklerken dönem borcunu ekstrendeki değerle kaydetmek, asgari ödeme ve kalan borç hesabının doğru başlamasını sağlar.",
    related: ["kredi-karti-ekstresi", "asgari-odeme", "son-odeme-tarihi"],
  },
  {
    slug: "devreden-bakiye",
    title: "Devreden bakiye",
    category: "Kredi kartı",
    definition: "Kredi kartı dönem borcundan yapılan ödemeler çıktıktan sonra sonraki döneme taşınan tutardır.",
    detail: "Dönem borcunun tamamı son ödeme tarihine kadar kapatılmadığında kalan bölüm devreden bakiye haline gelir. Yeni harcamalar, maliyetler ve sonraki ödemeler bu bakiyeyi değiştirebilir; bu yüzden yalnızca kart limitine bakmak gerçek borç durumunu göstermez.",
    example: "24.000 TL dönem borcuna 10.000 TL ödeme yaptıysan, başka düzeltme yoksa 14.000 TL sonraki döneme devreder.",
    borcama: "Ödeme girdikçe kalan kart borcu güncellenir; devreden tutarı diğer kart ve kredilerinden ayrı görebilirsin.",
    related: ["donem-borcu", "akdi-faiz", "gecikme-faizi"],
  },
  {
    slug: "kredi-karti-ekstresi",
    title: "Kredi kartı ekstresi",
    category: "Kredi kartı",
    definition: "Kartın belirli hesap dönemindeki işlemlerini, borcunu ve ödeme tarihlerini gösteren banka belgesidir.",
    detail: "Ekstrede dönem borcu, asgari ödeme, hesap kesim tarihi, son ödeme tarihi, taksitler, ücretler ve dönem içi işlemler yer alabilir. Güncel kart bakiyesiyle karıştırılmamalıdır; ekstre kesildikten sonraki işlemler henüz bu belgede bulunmaz.",
    example: "Eylül ekstresi 6 Ağustos–5 Eylül arasındaki işlemleri gösterebilir. 6 Eylül'de yapılan alışveriş çoğunlukla bir sonraki ekstreye yansır.",
    borcama: "Ekstre dosyası cihazında okunur; kaydetmeden önce dönem borcunu ve işlem kategorilerini sen kontrol edersin.",
    related: ["donem-borcu", "hesap-kesim-tarihi", "son-odeme-tarihi"],
  },
  {
    slug: "hesap-kesim-tarihi",
    title: "Hesap kesim tarihi",
    category: "Kredi kartı",
    definition: "Kredi kartının o ayki ekstresine girecek işlemlerin hesaplandığı tarihtir.",
    detail: "Hesap kesim tarihi geldiğinde banka ilgili dönemin ekstresini oluşturur. Bu tarihten sonra yapılan işlemler genellikle sonraki ekstre dönemine kalır; ancak kesin yansıma zamanı işlemin bankada muhasebeleşmesine göre değişebilir.",
    example: "Hesap kesim tarihin ayın 10'uysa, 11'inde muhasebeleşen bir harcama çoğunlukla sonraki ayın ekstresinde görünür.",
    borcama: "Kart kaydındaki hesap kesim tarihi, hangi borcun hangi ayın planına ait olduğunu ayırmana yardımcı olur.",
    related: ["kredi-karti-ekstresi", "son-odeme-tarihi", "donem-borcu"],
  },
  {
    slug: "son-odeme-tarihi",
    title: "Son ödeme tarihi",
    category: "Kredi kartı",
    definition: "Ekstrede belirtilen ödemenin gecikmeye düşmeden yapılması gereken son gündür.",
    detail: "Son ödeme tarihi hesap kesim tarihinden farklıdır. Banka bu tarihe kadar en az ekstredeki asgari tutarın ödenmesini bekler; tatil günü ve işlem saati gibi ayrıntılar için bankanın bildirimini esas almak gerekir.",
    example: "Ekstre 8 Eylül'de kesilip son ödeme tarihi 18 Eylül olarak belirlenmişse, planında ödeme gününü 18 Eylül'den önceye koyabilirsin.",
    borcama: "Ödeme günlerini aylık takvimde sıralayarak yaklaşan kart ve kredi ödemelerini birlikte görebilirsin.",
    related: ["hesap-kesim-tarihi", "asgari-odeme", "gecikme-faizi"],
    tool: "aylik-odeme-takvimi",
  },
  {
    slug: "akdi-faiz",
    title: "Akdi faiz",
    category: "Faiz ve maliyet",
    definition: "Kredi veya kart sözleşmesinde belirlenen, borcun normal kullanım koşullarındaki faiz oranıdır.",
    detail: "Akdi faiz ile gecikme faizi aynı değildir. Hangi bakiyeye, hangi tarihler arasında ve hangi vergilerle uygulanacağı ürün sözleşmesine bağlıdır; kredi kartlarında güncel azami oranlar TCMB tarafından yayımlanır.",
    example: "Kart borcunun tamamını kapatmadığında devreden tutara uygulanacak normal dönem maliyetinin temel bileşenlerinden biri akdi faizdir.",
    borcama: "Kendi oranını girdiysen hesaplarda o kullanılır; oran yoksa uygun ürün için güncel resmî referans ayrı bir tahmin olarak değerlendirilir.",
    related: ["gecikme-faizi", "efektif-faiz-orani", "bsmv"],
    tool: "borc-kapatma-hesaplayici",
  },
  {
    slug: "gecikme-faizi",
    title: "Gecikme faizi",
    category: "Faiz ve maliyet",
    definition: "Ödenmesi gereken tutar vadesinde ödenmediğinde geciken bölüm için uygulanabilen faizdir.",
    detail: "Gecikme faizinin matrahı ve başlangıç tarihi ürünün türüne ve sözleşmesine göre değişir. Kredi kartı, kredi taksiti ve ek hesap aynı kuralla hesaplanmayabilir; kesin tutar için banka ekstresi ve ödeme planı esas alınmalıdır.",
    example: "Son ödeme tarihinde gereken tutarın bir kısmı eksik kalırsa banka, geciken bölüm için sözleşmedeki kurala göre maliyet hesaplayabilir.",
    borcama: "Ödeme tarihlerini tek takvimde tutmak, gecikme riskini ödeme gerçekleşmeden görmene yardımcı olur.",
    related: ["akdi-faiz", "son-odeme-tarihi", "devreden-bakiye"],
  },
  {
    slug: "efektif-faiz-orani",
    title: "Efektif faiz oranı",
    category: "Faiz ve maliyet",
    definition: "Bir finansman ürününün faiz dışındaki zorunlu maliyetlerini ve zaman etkisini de hesaba katan karşılaştırma oranıdır.",
    detail: "İlan edilen nominal oran tek başına kredinin toplam maliyetini göstermeyebilir. Efektif oran, ödeme sıklığı ve zorunlu maliyetleri ortak bir ölçüye çevirmeyi amaçlar; farklı ürünleri aynı vade ve tutarda karşılaştırırken daha açıklayıcıdır.",
    example: "Aynı aylık faiz oranını sunan iki krediden biri ek zorunlu maliyet içeriyorsa efektif maliyeti daha yüksek olabilir.",
    borcama: "Kredi kaydında yalnızca taksite değil, toplam geri ödemeye ve kalan maliyete birlikte bakmak karşılaştırmayı kolaylaştırır.",
    related: ["akdi-faiz", "toplam-geri-odeme", "aylik-taksit"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "bsmv",
    title: "BSMV",
    category: "Faiz ve maliyet",
    definition: "Banka ve Sigorta Muameleleri Vergisi'nin kısaltmasıdır; bazı bankacılık işlemlerinde verginin bir parçası olarak tahsil edilir.",
    detail: "BSMV'nin uygulanıp uygulanmadığı ve matrahı işlem türüne göre değişebilir. Faiz oranıyla aynı şey değildir; kredi, kart veya ek hesap maliyetini hesaplarken sözleşmede gösterilen vergi kalemleri ayrıca kontrol edilmelidir.",
    example: "Bir finansman maliyeti faiz ve BSMV kalemlerini ayrı gösteriyorsa toplam aylık yük bu kalemlerin birlikte değerlendirilmesiyle bulunur.",
    borcama: "Borç planında banka oranı ve ilgili vergi bileşenleri ayrı tutulabildiği için tahminin dayanağını görebilirsin.",
    related: ["kkdf", "akdi-faiz", "efektif-faiz-orani"],
  },
  {
    slug: "kkdf",
    title: "KKDF",
    category: "Faiz ve maliyet",
    definition: "Kaynak Kullanımını Destekleme Fonu kesintisinin kısaltmasıdır ve bazı kredi işlemlerinde maliyete eklenebilir.",
    detail: "KKDF her finansman ürününde aynı biçimde uygulanmaz. Ürün türü, kullanım amacı ve güncel mevzuat sonucu etkileyebileceğinden kesin oranı kredi sözleşmesi ve banka ödeme planından kontrol etmek gerekir.",
    example: "Kredi ödeme planında faiz, BSMV ve KKDF ayrı satırlarda gösteriliyorsa taksit maliyeti bu bileşenlerin toplamını içerir.",
    borcama: "Ödeme planını aktarırken kalan anapara ile kalan faiz ve masrafı ayırmak, toplam yükü daha doğru okumana yardım eder.",
    related: ["bsmv", "toplam-geri-odeme", "kalan-anapara"],
  },
  {
    slug: "kalan-anapara",
    title: "Kalan anapara",
    category: "Kredi",
    definition: "Bir kredide, yapılan anapara ödemeleri düşüldükten sonra henüz geri ödenmemiş asıl borç tutarıdır.",
    detail: "Kalan anapara, kalan taksitlerin toplamı değildir. Gelecek taksitler çoğunlukla anapara ile birlikte faiz, vergi ve diğer sözleşmesel maliyetleri de içerir; bu nedenle toplam ödeme kalan anaparadan yüksek olabilir.",
    example: "Kalan anapara 100.000 TL iken gelecekteki taksitlerin toplamı 118.000 TL olabilir. Aradaki fark planlanan faiz ve diğer maliyetlerden oluşur.",
    borcama: "Kredi kartında kalan anapara, kalan toplam ödeme ve kalan faiz/masraf ayrı alanlarda gösterilir.",
    related: ["toplam-geri-odeme", "aylik-taksit", "borc-yapilandirma"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "toplam-geri-odeme",
    title: "Toplam geri ödeme",
    category: "Kredi",
    definition: "Bir kredi veya yapılandırmada ödeme planı boyunca ödenecek taksitlerin toplamıdır.",
    detail: "Toplam geri ödeme; anapara, faiz ve sözleşmeye göre taksitlere yansıyan diğer maliyetleri içerir. Erken ödeme, gecikme veya oran değişikliği gibi durumlarda gerçek toplam ödeme ilk plandan farklılaşabilir.",
    example: "36 ay boyunca 5.000 TL taksit ödenecekse planlanan toplam geri ödeme 180.000 TL'dir; bunun tamamı anapara değildir.",
    borcama: "Kredi satırında kalan taksit sayısı ile aylık taksiti kullanarak kalan toplam ödemeyi, anaparadan ayrı izleyebilirsin.",
    related: ["kalan-anapara", "aylik-taksit", "efektif-faiz-orani"],
  },
  {
    slug: "aylik-taksit",
    title: "Aylık taksit",
    category: "Kredi",
    definition: "Kredi ödeme planında belirli bir ay için ödenmesi planlanan tutardır.",
    detail: "Taksit yalnızca anapara ödemesinden oluşmaz; plana göre faiz ve diğer maliyetler de içerebilir. Eşit taksitli bir kredide tutar sabit görünse de taksit içindeki anapara ve faiz dağılımı zamanla değişebilir.",
    example: "Aylık taksitin 7.500 TL olması, anaparanın her ay tam 7.500 TL azalacağı anlamına gelmez.",
    borcama: "Aylık taksitler ödeme gününe göre takvime gelir; ödediğinde ilgili ayın kaydı ve kalan taksit bilgisi güncellenir.",
    related: ["kalan-anapara", "toplam-geri-odeme", "son-odeme-tarihi"],
    tool: "kredi-odeme-plani-hesaplama",
  },
  {
    slug: "ek-hesap-kmh",
    title: "Ek hesap (KMH)",
    category: "Borç yönetimi",
    definition: "Vadesiz hesaba tanımlanan ve bakiye yetersizken kullanılabilen kredili mevduat hesabıdır.",
    detail: "KMH kullanıldığında hesap eksi bakiyeye geçer ve kullanılan tutar için ürün koşullarına göre maliyet oluşabilir. Limit, kullanılabilir tutarı; açık bakiye ise gerçekten kullanılan borcu gösterir. Bu iki rakam aynı değildir.",
    example: "50.000 TL limitli ek hesabın 12.000 TL eksi bakiyedeyse açık borcun 12.000 TL, kalan kullanılabilir limitin kabaca 38.000 TL'dir.",
    borcama: "Ek hesap borcunu sıfırladıktan sonra yeniden kullandığında aynı hesaba yeni borç ekleyebilir ve eski ödemeleri koruyabilirsin.",
    related: ["nakit-akisi", "akdi-faiz", "borc-yapilandirma"],
  },
  {
    slug: "borc-yapilandirma",
    title: "Borç yapılandırma",
    category: "Borç yönetimi",
    definition: "Mevcut borcun yeni vade, taksit veya maliyet koşullarıyla yeniden ödeme planına bağlanmasıdır.",
    detail: "Yapılandırma aylık ödemeyi düşürebilir ama vade uzadığında toplam geri ödeme artabilir. Karar verirken yalnızca yeni taksite değil, toplam maliyete, erken ödeme koşullarına ve mevcut borcun nasıl kapanacağına birlikte bakılmalıdır.",
    example: "Aylık 15.000 TL ödeme 8.000 TL'ye düşerken vade uzuyorsa kısa vadeli rahatlama karşılığında toplam geri ödeme yükselebilir.",
    borcama: "Yapılandırılmış borcu kart bakiyesinden ayırıp ayrı kredi planı olarak izlemek çifte sayımı önler.",
    related: ["toplam-geri-odeme", "aylik-taksit", "efektif-faiz-orani"],
    tool: "borc-odeme-plani",
  },
  {
    slug: "nakit-akisi",
    title: "Nakit akışı",
    category: "Bütçe",
    definition: "Belirli bir dönemde giren ve çıkan paranın zaman ve tutar olarak hareketidir.",
    detail: "Gelir toplamının gider toplamından yüksek olması tek başına yeterli olmayabilir; ödeme günleri maaştan önce geliyorsa ay içinde geçici açık oluşabilir. Nakit akışı bu nedenle hem tutarı hem de zamanı birlikte ele alır.",
    example: "Ayda 50.000 TL gelir ve 45.000 TL giderin olsa bile 30.000 TL ödeme maaştan önceyse kısa süreli nakit ihtiyacı doğabilir.",
    borcama: "Gelir, sabit gider ve ödeme günlerini aynı ayda görerek hangi tarihte ne kadar alanın kaldığını takip edebilirsin.",
    related: ["butce-acigi", "net-varlik", "son-odeme-tarihi"],
    tool: "aylik-odeme-takvimi",
  },
  {
    slug: "butce-acigi",
    title: "Bütçe açığı",
    category: "Bütçe",
    definition: "Bir dönemde planlanan gider ve ödemelerin kullanılabilir gelirden fazla olmasıdır.",
    detail: "Bütçe açığı her zaman toplam servetin negatif olduğu anlamına gelmez. Aylık gelir-gider dengesi ile net varlık farklı ölçülerdir; düzenli açık sürerse borçlanma veya varlık tüketimi gerektirebilir.",
    example: "Aylık kullanılabilir gelirin 40.000 TL, gider ve zorunlu ödemelerin 47.000 TL ise planlanan açık 7.000 TL'dir.",
    borcama: "Aylık planda gelir, zorunlu ödeme ve yaşam giderlerini bir araya getirerek açığın hangi kalemlerden oluştuğunu görebilirsin.",
    related: ["nakit-akisi", "net-varlik", "borc-kapatma-plani"],
  },
  {
    slug: "net-varlik",
    title: "Net varlık",
    category: "Bütçe",
    definition: "Toplam varlıklardan toplam borçlar çıkarıldığında kalan finansal değerdir.",
    detail: "Net varlık aylık nakit akışından farklıdır. O ay gelir fazlan olabilir ama toplam borçların varlıklarından yüksekse net varlığın negatif kalabilir; düzenli takip yönün iyileşip iyileşmediğini gösterir.",
    example: "300.000 TL varlığın ve 220.000 TL toplam borcun varsa net varlığın 80.000 TL'dir.",
    borcama: "Nakit, mevduat ve diğer varlıkları borçlarınla aynı tabloda izleyerek net durumdaki değişimi görebilirsin.",
    related: ["nakit-akisi", "butce-acigi", "kalan-anapara"],
  },
  {
    slug: "borc-kapatma-plani",
    title: "Borç kapatma planı",
    category: "Borç yönetimi",
    definition: "Borçların hangi sırayla ve hangi aylık bütçeyle azaltılacağını gösteren uygulanabilir ödeme yol haritasıdır.",
    detail: "Sağlıklı plan, bütün borçları ve zorunlu ödemeleri görür; sürdürülebilir aylık bütçeyi kullanır ve kapanan borcun ödemesini sıradaki borca aktarır. En yüksek maliyeti veya en küçük bakiyeyi önceleme gibi farklı yöntemler seçilebilir.",
    example: "Bir kart kapandığında ona ayırdığın 4.000 TL'yi harcamaya döndürmek yerine sıradaki borcun ödemesine eklemek planı hızlandırır.",
    borcama: "Borç Planı kart, kredi ve ek hesaplarını gelir-gider tablonla birlikte değerlendirerek kapanış sırası oluşturur.",
    related: ["borc-yapilandirma", "butce-acigi", "toplam-geri-odeme"],
    tool: "borc-odeme-plani",
  },
];

export const FINANSAL_SOZLUK_KATEGORILERI = [...new Set(FINANSAL_SOZLUK.map((terim) => terim.category))];

export function finansalSozlukTerimi(slug) {
  return FINANSAL_SOZLUK.find((terim) => terim.slug === slug);
}
